src/components/dropdown/Dropdown.vue

Hi!
I've just modified the methods to check for a strictly null.

primefaces/primevue#11 Modified the Dropdown to not ignore a falsy value

---

src/components/dropdown/Dropdown.d.ts
src/components/dropdown/Dropdown.vue
src/views/dropdown/DropdownDoc.vue

The Dropdown component now supports the appendTo property.

Add appendTo on Dropdown

---

src/components/tooltip/Tooltip.d.ts

Added src/components/Tooltip/Tooltip.d.ts
Closes #202

Added Tooltip.d.ts

---

src/views/dataview/DataViewDoc.vue
src/views/splitbutton/SplitButtonDoc.vue

Doc urls fixed

---

src/components/treetable/TreeTable.vue

Though i have not looked much into it but possible fix for global filter in treetable

fix for global filter in treetable

---

src/views/message/MessageDemo.vue
src/views/message/MessageDoc.vue

InlineMessage `severity` property example added as in PrimeNG and PrimeReact

Added InlineMessage to views

---

src/views/datatable/DataTableColResizeDemo.vue

I've added `.p-datatable-gridlines` class. It might be easier to see where grid line is.

DataTable ColResize gridline

---

src/components/column/Column.d.ts
src/components/column/Column.vue
src/components/datatable/DataTable.d.ts
src/components/datatable/TableHeader.vue
src/components/dataview/DataView.d.ts
src/components/dataview/DataView.vue

Fixed "sortField" prop type in Column, DataTable, TableHeader and DataView (PrimeVue 3)

---

src/components/autocomplete/AutoComplete.vue

- highlight first element on 'ArrowDown'

Fixed #723: Keyboard support for AutoComplete

---

src/components/slider/Slider.vue

Slider: handle mixed-sign min/max attributes when positioning handle

---

src/components/api/Api.d.ts

Fix type declarations in Api.d.ts

---

src/views/calendar/CalendarDoc.vue

Addresses - https://github.com/primefaces/primevue/issues/1236

view property description fix

---

src/components/cascadeselect/CascadeSelect.d.ts
src/views/cascadeselect/CascadeSelectDoc.vue

fix CascadeSelectProp.optionGroupChildren type

---

src/views/confirmdialog/ConfirmDialogDemo.vue
src/views/confirmdialog/ConfirmDialogDoc.vue

fix ConfirmDialog example and documentation
replaced 'key' with 'group'

fix ConfirmDialog example and documentation

---

src/components/config/PrimeVue.d.ts

usePrimeVue ts declaration is wrong : PrimeVueConfiguration must be under config

Wrong typescript declaration for usePrimeVue

---

src/views/steps/SeatDemo.vue

vagon => wagon
Super small fix for the Step demo where Wagaon is sometimes (and internally) spelled with a v.

Update SeatDemo.vue typo

---

src/components/datatable/ColumnFilter.vue

[Fix #1532] DataTable - Implements showClearButton property

---

src/components/autocomplete/AutoComplete.d.ts
src/components/autocomplete/AutoComplete.vue
src/views/autocomplete/AutoCompleteDoc.vue

Fixes #1362 
Added ``autoHighlight`` property to AutoComplete, so when typing the first letters, just click enter (to add first entry needed ) instead of mouse down, it's a good UX approach!

[Feature Request]: Added autoHighlight property to AutoComplete

---

src/views/setup/Setup.vue

Correct file location for tailwind theme

Update Setup.vue docs

---

src/components/confirmationoptions/ConfirmationOptions.d.ts

This PR fixes #1852. It resolves a typescript build error.

fix: added header and blockScroll props to confirmationoptions.d.ts

---

src/components/dock/Dock.d.ts
src/components/speeddial/SpeedDial.d.ts

Fixes [#1945 ](https://github.com/primefaces/primevue/issues/1945)

tooltip errors in d.ts

---

src/components/menuitem/MenuItem.d.ts

MenuItem: change 'to' type to RouteLocationRaw

---

src/components/tag/Tag.vue

Tag - show icon whether slot is used or not

---

src/components/panelmenu/PanelMenuSub.vue

[fix]panelMenuSub isActive bug in 2.8.0

---

api-generator/components/toolbar.js

https://primefaces.org/primevue/showcase/#/toolbar

Toolbar: Align slot names with implementation and docs

---

src/components/organizationchart/OrganizationChart.d.ts

Define OrganizationChartProps::value as "OrganizationChartNode"

---

src/components/treetable/FooterCell.vue

Fix typo in Treetable/FooterCell

---

src/views/datatable/DataTableScrollDemo.vue
src/views/treetable/TreeTableScrollDemo.vue

Fix documentation typos

---

src/views/menu/MenuDoc.vue

> When submitting a PR, please also create an issue documenting the error.
Hence it only fixes a typo I assume there is no need to create an issue

Fix menu demo quotes

---

src/components/panelmenu/PanelMenu.vue
src/components/panelmenu/PanelMenuSub.vue

Fixes #2181 by taking the `@keydown` action from Accordion and applying them to PanelMenu.

Fix #2181: PanelMenu 508 compliance issue

---

src/views/menubar/MenubarDoc.vue

This small PR fixes the quotation mark in the Menubar doc

Fix quotation mark in doc

---

api-generator/components/dialog.js

Fix draggable description

---

src/components/confirmpopup/ConfirmPopup.vue

fix: align overlay dynamically

---

api-generator/components/timeline.js
src/components/timeline/Timeline.d.ts

fix: type TimelineVerticalAlignType declaration #2367

---

api-generator/components/panelmenu.js

Fix PanelMenu Doc

---

src/views/panelmenu/PanelMenuDoc.vue

Fix panelmenu demo quotes in documentation

---

src/components/datatable/DataTable.vue
src/components/datatable/TableBody.vue

Fix loading template on DataTable component

---

src/components/calendar/Calendar.spec.js
src/components/calendar/Calendar.vue

Fix calendar selecting time when in range mode

---

public/demo/data/countries.json

Taiwan is NOT a Province of China.

Political Issue

---

src/components/steps/Steps.vue

Fix current tab for named routes in Steps 

---

src/components/autocomplete/AutoComplete.vue
src/views/autocomplete/AutoCompleteDoc.vue

Add new prop to allow users to pass in the loader icon

---

src/components/inputnumber/InputNumber.vue

See related issue : https://github.com/primefaces/primevue/issues/1518

Add 'tab' key support on Input Number

---

src/components/tooltip/Tooltip.js

Clear ZIndex on tooltip element instead of target element

---

src/components/multiselect/MultiSelect.vue
src/views/multiselect/MultiSelectDemo.vue
src/views/multiselect/MultiSelectDoc.vue

resolves #2481 added a method for clearing the filter input

---

src/components/datatable/HeaderCheckbox.vue

Add disable class to the outer div of DTHeaderCheckbox

---

src/components/calendar/Calendar.vue
src/components/portal/Portal.vue

Closes https://github.com/primefaces/primevue/issues/2689
Tested on Nuxt v.3.0.0-rc.4 to verify Portal isn't broken and works under SSR

Fix Portal isClient detection, fix onBlur method in Calendar - fixes #2689

---

src/views/calendar/CalendarDoc.vue

There were three closing curly brackets where there should have been two. I removed one of them
^ normally i would do this, but it's really not worth it for a change this small. let me know if it's really needed for this
#2701

Update CalendarDoc.vue: typo fix

---

src/components/calendar/Calendar.d.ts

Retyped calendar date slotprop

---

src/components/datatable/BodyCell.vue

Check which edit mode when calling editor save callback and editor cancel callback

---

src/views/megamenu/MegaMenuDoc.vue

Fix erroneous quotation marks in class attribute binding
https://github.com/primefaces/primevue/issues/2816

Syntax error fix

---

api-generator/components/button.js
src/components/button/Button.d.ts
src/components/button/Button.vue
src/views/button/ButtonDemo.vue
src/views/button/ButtonDoc.vue

Bring the loading prop feature from vue3 to vue2

Bringing button loading prop from vue 3 in vue 2

---

src/components/calendar/Calendar.vue

Fixed #2803 inline calendar autofocus when disabledDates changed

---

src/views/confirmpopup/ConfirmPopupDoc.vue

Content class is called 'p-confirm-popup-content', not 'p-confirm-content'

Fix: Content Class

---

src/components/password/Password.vue

Password component meter cannot set dynamically. This issue solved

Password meter dynamic changes problem solved

---

api-generator/components/carousel.js
src/components/carousel/Carousel.d.ts
src/components/carousel/Carousel.vue
src/views/carousel/CarouselDoc.vue

- showNavigators and  showIndicators props added for display controls.

Display control props added to carousel component

---

src/views/steps/StepsDemo.vue

Steps component demo issue fixed

Demo issue fixed

---

src/components/tabmenu/TabMenu.vue
src/views/tabmenu/TabMenuDemo.vue
src/views/tabmenu/TabMenuDoc.vue

TabMenu accessibility improvements

Tabmenu changes for accessibility

---

api-generator/components/dropdown.js
src/components/dropdown/Dropdown.d.ts
src/components/dropdown/Dropdown.spec.js
src/components/dropdown/Dropdown.vue
src/views/dropdown/DropdownDoc.vue

Add custom icons support for Dropdown component

---

api-generator/components/autocomplete.js
src/components/autocomplete/AutoComplete.d.ts
src/components/autocomplete/AutoComplete.spec.js
src/components/autocomplete/AutoComplete.vue
src/views/autocomplete/AutoCompleteDoc.vue

Add custom icons support for AutoComplete component

---

api-generator/components/listbox.js
src/components/listbox/Listbox.d.ts
src/components/listbox/Listbox.spec.js
src/components/listbox/Listbox.vue
src/views/listbox/ListboxDoc.vue

Add custom icons support for Listbox component

---

api-generator/components/multiselect.js
src/components/multiselect/MultiSelect.d.ts
src/components/multiselect/MultiSelect.spec.js
src/components/multiselect/MultiSelect.vue
src/views/multiselect/MultiSelectDoc.vue

Add custom icons support for Multiselect component

---

api-generator/components/cascadeselect.js
src/components/cascadeselect/CascadeSelect.d.ts
src/components/cascadeselect/CascadeSelect.spec.js
src/components/cascadeselect/CascadeSelect.vue
src/components/cascadeselect/CascadeSelectSub.vue
src/views/cascadeselect/CascadeSelectDoc.vue

Add custom icons support for CascadeSelect component

---

src/components/cascadeselect/CascadeSelect.vue

input-text class added to CascadeSelect component

input-text class added

---

src/components/toast/ToastMessage.vue

Toast component close icon style issue fixed.
#2949

toast close icon style issue fixed

---

src/components/inputtext/InputText.css

Inputtext floating label placeholder bug fixed

---

src/components/galleria/GalleriaThumbnails.vue

Galleria slide issue fixed

---

src/components/ripple/Ripple.js

Fixed cases where ripple is triggered when not properly destroyed

Fixed cases where ripple is triggered when not properly destroyed

---

src/Home.vue
src/components/calendar/Calendar.vue

I've documented the issue here.
https://github.com/primefaces/primevue/issues/3032

Calendar: Fix keyboard support when there is a disable date next to the focused date

---

api-generator/components/datatable.js
api-generator/components/paginator.js
src/components/datatable/DataTable.d.ts
src/components/paginator/Paginator.d.ts
src/components/paginator/Paginator.vue
src/views/datatable/DataTablePaginatorDemo.vue
src/views/paginator/PaginatorDemo.vue
src/views/paginator/PaginatorDoc.vue

Paginator breakpoints

---

src/components/tree/Tree.d.ts

Tree node icon types added

---

src/components/tabmenu/TabMenu.vue

TabMenu: accessibility updates

---

package-build.json

build(package.json): update icon version

---

src/components/slider/Slider.vue

Slider range changes related [https://github.com/primefaces/primeng/issues/11427](prime-ng-pr)
Fixed #3104

Slider range changes completed

---

src/components/multiselect/MultiSelect.spec.js
src/components/multiselect/MultiSelect.vue

Issue created:- https://github.com/primefaces/primevue/issues/3068

Fix MultiSelect group display when filtering

---

src/components/multiselect/MultiSelect.vue

Multiselect cannot all select when has a disabled option issue

---

src/components/calendar/Calendar.vue

Calendar input focus undefined problem fixed

---

src/components/dropdown/Dropdown.vue

Dropdown option group disappear when filter item 

---

src/components/breadcrumb/BreadcrumbItem.vue

Window removed from breadcrumb component

---

src/components/overlaypanel/OverlayPanel.d.ts

Missing type added

---

api-generator/components/dialog.js
src/components/dialog/Dialog.d.ts
src/components/dialog/Dialog.spec.js
src/components/dialog/Dialog.vue
src/views/dialog/DialogDoc.vue

Add custom icons support for the Dialog component

---

api-generator/components/sidebar.js
src/components/sidebar/Sidebar.d.ts
src/components/sidebar/Sidebar.spec.js
src/components/sidebar/Sidebar.vue
src/views/sidebar/SidebarDoc.vue

Allow custom icon support for the Sidebar component

---

api-generator/components/message.js
src/components/message/Message.d.ts
src/components/message/Message.spec.js
src/components/message/Message.vue
src/views/message/MessageDoc.vue

Allow custom close icon for the Message component

---

api-generator/components/toast.js
src/components/toast/Toast.d.ts
src/components/toast/Toast.spec.js
src/components/toast/Toast.vue
src/components/toast/ToastMessage.vue
src/views/toast/ToastDoc.vue

Allow custom icons for the Toast component

---

api-generator/components/calendar.js
src/components/calendar/Calendar.d.ts
src/components/calendar/Calendar.spec.js
src/components/calendar/Calendar.vue
src/views/calendar/CalendarDoc.vue

Allow custom icons for the calendar component

---

api-generator/components/inplace.js
src/components/inplace/Inplace.d.ts
src/components/inplace/Inplace.spec.js
src/components/inplace/Inplace.vue
src/views/inplace/InplaceDoc.vue

Add custom icons support for Inplace component

---

api-generator/components/dialog.js
src/components/dialog/Dialog.d.ts
src/components/dialog/Dialog.spec.js
src/components/dialog/Dialog.vue
src/views/dialog/DialogDoc.vue

Add custom support for minimize and maximize icons in dialog

---

src/components/paginator/Paginator.vue

Paginator setAttribute problem solved

---

src/components/menubar/Menubar.vue

Menu icon problem fixed

---

.github/workflows/issue-inactive-checker.yml
.github/workflows/issue-labeled.yml
.github/workflows/pr-checker.yml

Workflow Label changes

---

src/components/slider/Slider.vue

Slider range fixes

---

api-generator/components/chips.js
src/components/chips/Chips.d.ts
src/components/chips/Chips.vue
src/views/chips/ChipsDemo.vue
src/views/chips/ChipsDoc.vue

Chips sperator changes

---

src/components/calendar/Calendar.vue

Calendar: Jumping month fixed for inline calendars

---

src/components/radiobutton/RadioButton.css

RadioButton scroll to top issue fixed

---

src/components/slider/Slider.vue

[issu-3251](https://github.com/primefaces/primevue/issues/3251)

Slider : fix undefined modelValue in slider

---

src/components/blockui/BlockUI.vue
src/views/blockui/BlockUIDoc.vue

Improve blockUI implementation for accessibility

---

src/views/badge/BadgeDemo.vue
src/views/badge/BadgeDoc.vue

Improve Badge Implementation for Accessibility

---

src/views/progressbar/ProgressBarDoc.vue

improve progressBar implementation for accessibility

---

src/components/chip/Chip.vue
src/views/chip/ChipDoc.vue
src/views/progressbar/ProgressBarDoc.vue

Improve chip implementation for accessibility

---

src/components/inputnumber/InputNumber.vue

https://github.com/primefaces/primevue/issues/2980

Issue correction #2980

---

api-generator/components/avatar.js
src/components/avatar/Avatar.d.ts
src/components/avatar/Avatar.vue
src/views/avatar/AvatarDoc.vue

Avatar: Accessibility improvements

---

api-generator/components/sidebar.js
src/components/sidebar/Sidebar.d.ts
src/components/sidebar/Sidebar.vue
src/views/sidebar/SidebarDoc.vue
src/views/slider/SliderDoc.vue

Sidebar: Header slot added

---

src/components/password/Password.vue

Password component was not displaying default data. This problem is solved.

Password component default value display issue fixed

---

src/components/sidebar/Sidebar.vue

Adding header slot to sidebar like vue3 version of primevue to version of vue2

Adding header slot to sidebar like vue3 version of primevue to  version of vue2

---

src/components/calendar/Calendar.vue

Calendar: maxDate with 12-hour formatting restricts values incorrectly 

---

src/components/organizationchart/OrganizationChartNode.vue
src/views/organizationchart/OrganizationChartDoc.vue

Improve organizationchart implementation for accessibility

---

src/components/rating/Rating.vue

Rating: Fixed scroll to top problem

---

api-generator/components/tree.js
src/components/tree/Tree.d.ts
src/components/tree/Tree.vue
src/components/tree/TreeNode.vue
src/views/tree/TreeDoc.vue

Improve Tree implementation for accessibility

---

src/components/password/Password.vue

Eye icon duplicate problem fixed for IE

---

api-generator/components/speeddial.js
src/components/speeddial/SpeedDial.d.ts
src/components/speeddial/SpeedDial.vue
src/views/speeddial/SpeedDialDemo.vue
src/views/speeddial/SpeedDialDoc.vue

Improve SpeedDial Implementation for Accessibility

---

components/calendar/Calendar.vue

fix: calendar time, when writing pm in input

---

components/calendar/Calendar.d.ts

Calendar: Invalid TypeScript definitions for modelValue 

---

api-generator/components/sidebar.js
components/sidebar/Sidebar.d.ts
components/sidebar/Sidebar.spec.js
components/sidebar/Sidebar.vue
pages/sidebar/SidebarDoc.vue

Sidebar: reimplement

---

components/editor/Editor.vue

Editor: color format button rendering issue fixed

---

components/splitbutton/SplitButton.vue

SplitButton: default action problem fixed

---

components/breadcrumb/Breadcrumb.vue

Fixed home icon not displaying with slot

---

components/confirmdialog/ConfirmDialog.vue

ConfirmDialog: Icon rendering problem fixed

---

components/panel/Panel.vue
components/tabview/TabView.vue

Panel: Typo fixed for default props

---

api-generator/components/splitbutton.js
components/splitbutton/SplitButton.d.ts
components/splitbutton/SplitButton.vue
pages/splitbutton/SplitButtonDoc.vue

SplitButton: Button class style and dropdown icon customization

---

components/panelmenu/PanelMenu.vue

PanelMenu: passing computed value as a model prop fixed

---

components/sidebar/Sidebar.vue

Sidebar: non-props attributes issue

---

pages/focustrap/index.vue

Fixes: [#3528](https://github.com/primefaces/primevue/issues/3528)

Remove typo from page title

---

components/paginator/JumpToPageInput.vue
components/paginator/Paginator.vue

JumpToPageInput: changing input value issue fixed

---

pages/breadcrumb/BreadcrumbDoc.vue

fix: Breadcrumb documentation #3507

---

components/calendar/Calendar.vue

Fixed #3356 by correctly checking the am/pm status when incrementing minutes.

Calendar: allow modification of minute value on MaxDate

---

components/breadcrumb/Breadcrumb.vue

Breadcrumb: Home item slot changes

---

components/calendar/Calendar.vue

Issue #3589 
Disable the months and years number button when setting `minDate` or `maxDate`
I want it to be disabled because when I use it to be a Month Picker or Year Picker. Users don't understand why they can not press the button or press it but the input doesn't change.

Calendar: Disable year and month when set minDate or maxDate

---

doc/inlinemessage/ImportDoc.vue

Fixed wrong import documentation for InlineMessage

---

doc/deferredcontent/AccessibilityDoc.vue

Include missing closing quotation for `data > code > basic`
This will fix #3719

fix: Update AccessibilityDoc for DeferredContent

---

components/inputmask/InputMask.vue

InputMask: Dynamic mask change issue fixed

---

components/tooltip/Tooltip.js

fix trim undefined in tooltip.js

---

doc/radiobutton/GroupDoc.vue

Fixes: https://github.com/primefaces/primevue/issues/3757

Fix: RadioButton group documentation

---

components/dropdown/Dropdown.vue

Dropdown: selected disable option issue fixed

---

components/slider/Slider.spec.js
components/slider/Slider.vue

Slider: Accessibility and focus updates on drag

---

doc/theming/PrimeFlexDoc.vue

Fix spelling mistake in PrimeFlexDoc

---

api-generator/components/image.js
components/image/Image.d.ts
components/image/Image.vue

Image: Add Additional Toolbar Buttons

---

components/image/Image.d.ts
components/image/Image.vue

Image: Indicator icon props added

---

doc/installation/PropCasesDoc.vue

docs: typo kebap-case -> kebab-case

---

components/lib/calendar/Calendar.vue

**Issue: https://github.com/primefaces/primevue/issues/3811**

3811 Add year-change emit when nav Next or Prev

---

components/lib/galleria/GalleriaContent.vue
doc/galleria/AdvancedDoc.vue

Galleria: Play and Pause Feature

---

doc/inputnumber/ButtonsDoc.vue

changed decrementButtonclass and incrementButtonclass to decrementButtonClass/incrementButtonClass for InputNumber documentation
Issue link here: https://github.com/primefaces/primevue/issues/3856

Fix prop typo for button

---

components/lib/toast/ToastMessage.vue

Fix toast message template

---

api-generator/components/image.js
components/lib/image/Image.d.ts
components/lib/image/Image.vue
doc/image/PreviewDoc.vue

imagePreview slot added

---

components/lib/tooltip/Tooltip.d.ts
components/lib/tooltip/Tooltip.js
doc/tooltip/DelayDoc.vue
pages/tooltip/index.vue

Tooltip: Delay option

---

components/lib/calendar/Calendar.vue

Calendar: Fixed overlay visibility issue when showOnFocus

---

doc/inputtext/SizesDoc.vue

(typo) Use correct class names in description text

Inputtext: Update SizesDoc.vue

---

components/lib/tooltip/Tooltip.js

4025  fix undefined hide delay

---

components/lib/column/Column.d.ts

Fix sorticon slot props type in column component

fix: fix column sorticon slot props type

---

components/lib/panel/Panel.d.ts

Fix type of `id` prop in Panel `header` slot

---

components/lib/image/Image.vue

fix: fix image preview not closing on escape

---

components/lib/dropdown/BaseDropdown.vue

Fix: fix incorrect prop types in dropdown

---

doc/galleria/ThumbnailDoc.vue

Fix typo in Documentation: Missing 's' in style property

---

components/lib/toast/BaseToast.vue

fix: fixes icon shrink in toast

---

components/lib/tooltip/BaseTooltip.js

fix: fix tooltip flickering

---

components/lib/image/Image.vue

Fixes #2947 
This PR removes browser scrollbar while previewing image.

Image: Removed scrollbar for image preview

---

components/lib/calendar/Calendar.vue

Convert stepMinute / hour / second to Number

---

components/lib/message/BaseMessage.vue

fix: fix icon shrink when text message wraps to multiple lines.

---

components/lib/fileupload/BaseFileUpload.vue
components/lib/fileupload/FileUpload.vue

I added the SCSS style in https://github.com/primefaces/primevue-sass-theme/pull/14 because it's the correct place. But the others 2 lines are necessary to works OK
Fix #4129 
Following the same solution suggested in PrimeNG https://github.com/primefaces/primeng/pull/13326 and PrimeReact https://github.com/primefaces/primereact/pull/4646 for the same problem.
when I'm trying to drag over my file in the component (nothing was happening)

Added .p-fileupload-highlight class

---

api-generator/components/calendar.js

Fix typo and grammatical error in description for Calendar API

---

components/lib/calendar/Calendar.vue

Calendar: format 12 container focustrap issue

---

api-generator/components/splitbutton.js
components/lib/splitbutton/SplitButton.d.ts
components/lib/splitbutton/SplitButton.vue

SplitButton: Slot icon updates

---

src/components/calendar/Calendar.vue

Fixes https://github.com/primefaces/primevue/issues/3988

Calendar: Months are not highlighted with selection-mode="multiple"

---

components/lib/inputmask/InputMask.vue

InputMask: Paste issue solved

---

doc/confirmdialog/BasicDoc.vue

Only a small documentation update

ConfirmDialogDocumentation: Removed duplicated symbol

---

components/lib/image/Image.vue

fix: Fixes scrollbar break while closing image preview

---

doc/sidebar/pt/PTDoc.vue

Fix: Sidebar Docs missing quotes

---

doc/tabmenu/BasicDoc.vue
doc/tabmenu/RouterDoc.vue

Fixed 2 small typo errors on docs

Fix: Docs typo

---

components/lib/textarea/Textarea.vue

Textarea autoResize issue

---

components/lib/basecomponent/BaseComponent.vue

Fix buttonset styling when only a single button is present.

---

components/lib/confirmpopup/BaseConfirmPopup.vue
components/lib/confirmpopup/ConfirmPopup.vue

ConfirmPopup: acceptClass and rejectClass is not working on unstyled mode

---

components/lib/column/Column.d.ts

Column Filter: Add type for `applyFilter`

---

src/components/treetable/HeaderCell.vue
src/views/treetable/TreeTableTemplatingDemo.vue

TreeTable: Slot for custom column header in 2.x

---

components/lib/fileupload/FileUpload.vue

fix: Fixes input trigger on right mouse click

---

components/lib/calendar/Calendar.vue

Fix #4418: Calendar highlight selected months/years in multiple

Fix #4418: Calendar highlight selected months/years in multiple

---

components/lib/calendar/Calendar.vue

https://github.com/primefaces/primevue/issues/4449

fix: 12am changed to 12pm wrongly

---

components/lib/inlinemessage/style/InlineMessageStyle.js

fix: fix icon shrink in inlinemessage

---

components/doc/DocApiTable.vue

Fix issue #4601
PT options section should render without problems.

Fix issue #4601 - Passthrough options for components not showing in web documentation

---

.gitignore
components/lib/multiselect/MultiSelect.vue

Fix #4558 - Prioritize use "selectionMessage" from global config locale else use from props: "selectedItemsLabel"
Also added .idea directory to .gitignore (for Webstorm usage)

Fix #4558 - locale "selectedItemsLabel" is broken on MultiSelect

---

components/lib/calendar/Calendar.vue

Fix (https://github.com/primefaces/primevue/issues/4614) -  currentYear is not defined

Fix currentYear is not defined

---

components/lib/overlaypanel/BaseOverlayPanel.vue
components/lib/overlaypanel/OverlayPanel.d.ts
components/lib/overlaypanel/OverlayPanel.vue

fix #4620 Overlaypanel: Overlay panel doesnot close on escape button click

fix #4620 Overlaypanel: Overlay panel doesnot close on escape button click

---

components/lib/tooltip/style/TooltipStyle.js

fix: fix tooltip flicker on hover

---

components/lib/fileupload/FileUpload.vue

Fix #4667 - FileUpload: Basic uploader click
Related: https://github.com/primefaces/primevue/pull/4414

Fix #4667 - FileUpload: Basic uploader click

---

doc/panel/TemplateDoc.vue

Fix #4734 - PrimeVue docs inconsistency between code and output for Panel component

Fix #4734 - PrimeVue docs inconsistency between code and output for Panel component

---

components/lib/multiselect/MultiSelect.vue

MultiSelect selectedItemsLabel order

---

pages/uikit/index.vue

Fix #4754  
Preview Dark Mobile Responsive Issue

Fix Preview Dark Mobile Responsive Issue

---

components/lib/inputgroup/BaseInputGroup.vue
components/lib/inputgroup/InputGroup.d.ts
components/lib/inputgroup/InputGroup.vue
components/lib/inputgroup/package.json
components/lib/inputgroup/style/InputGroupStyle.d.ts
components/lib/inputgroup/style/InputGroupStyle.js
components/lib/inputgroup/style/package.json
components/lib/inputgroupaddon/BaseInputGroupAddon.vue
components/lib/inputgroupaddon/InputGroupAddon.d.ts
components/lib/inputgroupaddon/InputGroupAddon.vue
components/lib/inputgroupaddon/package.json
components/lib/inputgroupaddon/style/InputGroupAddonStyle.d.ts
components/lib/inputgroupaddon/style/InputGroupAddonStyle.js
components/lib/inputgroupaddon/style/package.json
modules/nuxt-primevue/runtime/core/components/index.js
nuxt-vite.config.js
rollup.config.js

New InputGroup Component

---

doc/dialog/theming/TailwindDoc.vue
doc/image/theming/TailwindDoc.vue

Update docs for: [#4650](https://github.com/primefaces/primevue/issues/4650), [#4653](https://github.com/primefaces/primevue/issues/4653)

Update docs for themeing unstyled

---

components/lib/baseicon/BaseIcon.vue

fix #4741: loading spinner not animated in multiselect

---

components/lib/datatable/DataTable.vue

Fix #4394 - DataTable VirtualScroller: resizableColumns broken

Fix #4394 - DataTable VirtualScroller: resizableColumns broken

---

components/lib/autocomplete/AutoComplete.vue

fix: #4749 || fix incorrect reference value display

---

components/lib/focustrap/FocusTrap.js

fix: primevue#4824

---

components/doc/codeeditor/services.js
service/PhotoService.js

fix: fix broken image links in galleria

---

components/lib/column/Column.d.ts

Fixed #4423: Column: Missing typing for sorticon

---

components/lib/editor/Editor.vue

Fix [#4872](https://github.com/primefaces/primevue/issues/4872): Editor's readonly prop does not react to any changes

Fix #4872: Editor's readonly prop does not react to any changes

---

doc/customicons/ImageDoc.vue

Corrected "any time of image" to "any type of image"

Fix: typo on doc for using images for custom icons

---

doc/installation/PluginDoc.vue

_As this is a simple docs fix, I haven't created an issue._

Update PluginDoc.vue - fix Nuxt link

---

api-generator/components/treetable.js
components/lib/treetable/BaseTreeTable.vue
components/lib/treetable/TreeTable.d.ts
components/lib/treetable/TreeTable.vue
components/lib/treetable/TreeTableRow.vue
doc/treetable/selection/CheckboxRowSelectionDoc.vue

#4273 Add support for dataKey on TreeTable

---

components/lib/image/style/ImageStyle.js

fix: fix image preview close on disabled zoom button click

---

components/lib/inputnumber/BaseInputNumber.vue
components/lib/inputnumber/InputNumber.d.ts
components/lib/inputnumber/InputNumber.vue

Fix: https://github.com/primefaces/primevue/issues/4945

Support `roundingMode` for `InputNumber`

---

components/lib/column/Column.d.ts

added sortIcon property to type ColumnPassThroughOptionType

---

components/lib/sidebar/Sidebar.vue

fix: fix escape keydown functionality in sidebar

---

components/lib/dialog/style/DialogStyle.js

fix: fix maximizable issue in Dialog component when moved 

---

components/lib/overlaypanel/OverlayPanel.d.ts

fix #5058: expose alignOverlay method in OverlayPanel

---

components/lib/datatable/HeaderCell.vue

fix: conditional check for sortable in HeaderCell.vue

---

components/lib/accordion/Accordion.vue
components/lib/autocomplete/AutoComplete.vue
components/lib/cascadeselect/CascadeSelect.vue
components/lib/contextmenu/ContextMenu.vue
components/lib/dock/DockSub.vue
components/lib/dropdown/Dropdown.vue
components/lib/listbox/Listbox.vue
components/lib/megamenu/MegaMenu.vue
components/lib/menu/Menu.vue
components/lib/menubar/Menubar.vue
components/lib/multiselect/MultiSelect.vue
components/lib/orderlist/OrderList.vue
components/lib/panelmenu/PanelMenu.vue
components/lib/picklist/PickList.vue
components/lib/speeddial/SpeedDial.vue
components/lib/tabview/TabView.vue
components/lib/tieredmenu/TieredMenu.vue

fix(#4953): use beforeMount to generate unique component id

---

components/lib/baseicon/BaseIcon.vue
components/lib/icons/arrowdown/index.vue
components/lib/icons/arrowup/index.vue
components/lib/icons/ban/index.vue
components/lib/icons/exclamationtriangle/index.vue
components/lib/icons/eyeslash/index.vue
components/lib/icons/filter/index.vue
components/lib/icons/filterslash/index.vue
components/lib/icons/infocircle/index.vue
components/lib/icons/pencil/index.vue
components/lib/icons/plus/index.vue
components/lib/icons/refresh/index.vue
components/lib/icons/search/index.vue
components/lib/icons/searchminus/index.vue
components/lib/icons/searchplus/index.vue
components/lib/icons/sortalt/index.vue
components/lib/icons/sortamountdown/index.vue
components/lib/icons/sortamountupalt/index.vue
components/lib/icons/spinner/index.vue
components/lib/icons/star/index.vue
components/lib/icons/starfill/index.vue
components/lib/icons/thlarge/index.vue
components/lib/icons/timescircle/index.vue
components/lib/icons/trash/index.vue
components/lib/icons/undo/index.vue
components/lib/icons/upload/index.vue
components/lib/icons/windowmaximize/index.vue
components/lib/icons/windowminimize/index.vue

Icon id hydration

---

components/lib/multiselect/MultiSelect.spec.js

Fixes the failing tests caused by #5105 related commits.

test(MultiSelect): update tests according to #5105

---

README.md

Update README.md - wrong link

---

components/lib/colorpicker/ColorPicker.d.ts
doc/common/apidoc/index.json

docs(color-picker): parameter field in emit change event is incorrect

---

doc/toast/StickyDoc.vue

Fix #5184 - Toast: Sticky option documentation enhancement

---

components/lib/colorpicker/ColorPicker.vue

fix(color-picker): change event only shows old color value

---

components/lib/dialog/Dialog.vue

fix: error in console on dragging dialog

---

doc/menu/RouterDoc.vue

Composition api not use this.$router. changed ref router 

Fixed Menu Doc Router Composition Api Push

---

components/lib/datatable/DataTable.vue

fix: fix select all in single selection mode on Ctrl-A press

---

doc/knob/MinMaxDoc.vue

Fix #5281 - Knob Min/Max Source Code

---

components/lib/calendar/Calendar.vue

resolves https://github.com/primefaces/primevue/issues/5312

fix(Calendar): expose same attrs to pt context for day and day label

---

doc/password/FilledDoc.vue

Fix #5314 - Filled Password Example

---

components/lib/selectbutton/SelectButton.d.ts

Add `disabled` to `SelectButtonContext` type

---

components/lib/terminal/Terminal.vue

fix: https://github.com/primefaces/primevue/issues/5364

fix: use KeyboardEvent `key` instead of `code`

---

components/lib/inputotp/InputOtp.vue

fix: incorrect inputmode

---

components/lib/inputnumber/InputNumber.vue

Fix #3928: InputNumber allow cut and paste
Similar to fix in PrimeReact: https://github.com/primefaces/primereact/pull/6193

Fix #3928: InputNumber allow cut and paste

---

doc/splitbutton/BasicDoc.vue

doc(splitbutton): fix composition API composable use

---

components/lib/multiselect/MultiSelect.vue

fix: duplicate values on search in multiselect

---

components/lib/fileupload/FileUpload.vue

fix(FileUpload): pass disable prop to Button in basic mode, fixes #5529

---

components/lib/autocomplete/AutoComplete.vue

#5618 - Updated AutoComplete to allow form submission using return

---

doc/nuxt/configuration/DirectivesDoc.vue

docs(DirectivesDoc.vue): typo

---

components/lib/colorpicker/ColorPicker.vue

Fix #5671: Unused codes removed

Fix #5671: Unused codes removed

---

components/lib/inputnumber/InputNumber.vue

Adds a button type to html button element to prevent form submits when placed within a form.
Fixes #5700

fix(InputNumber): add button type attribute, fixes #5700

---

components/lib/calendar/Calendar.vue

Fix #5687: delete month parameter on onMonthSelect 

---

components/lib/datepicker/DatePicker.vue

This commit is a copy of PR #5607 for the v4 branch. Since the component was renamed, the fix from the master branch was not applied to the new component.
Fixes #5596 and others for v4 branch (new component name)

fix(DatePicker): set hour on 24h mode on date select, fixes #5596

---

components/lib/datepicker/DatePicker.vue

DatePicker - V4: focus blink fix

---

doc/menu/TemplateDoc.vue

docs(TemplateDoc.vue) Remove unused Tailwind CSS class

---

doc/clt/UninstallDoc.vue

Updated uninstally text in primeclt to uninstall

fix: change uninstally to uninstall

---

components/lib/inputotp/InputOtp.vue

fix: paste function bug in integerOnly mode

---

components/lib/tieredmenu/TieredMenu.vue

fix: tiered menu popup not closing on escape

---

components/lib/inplace/Inplace.vue

fix: focus trap issue in Inplace

---

components/lib/confirmpopup/ConfirmPopup.vue
components/lib/dialog/Dialog.vue

Fixes: https://github.com/primefaces/primevue/issues/5777

fix: Dialog/Confirm re-focus original element on close

---

components/lib/inputnumber/InputNumber.vue

fix: incorrect default value for minFractionDigits when set to null 

---

packages/themes/src/presets/aura/menu/index.js

remove extraneous .

---

apps/showcase/assets/menu/menu.json

Fixes the changelog url that changed with #5774

fix(docs): update changelog url

---

apps/showcase/components/doc/codeeditor/templates.js

* Update primevue version to 4.0.0-rc.2 in codeeditor
* Add missing @primevue/themes package in codeeditor

fix(docs): Update primevue version and add missing @primevue/themes package in codeeditor

---

packages/primevue/src/tooltip/style/TooltipStyle.js

- fix #5916
|before|after|
|---|---|
|<img width="420" alt="스크린샷 2024-06-19 오전 8 36 22" src="https://github.com/primefaces/primevue/assets/37934668/66f6db6d-bfc1-4fe0-a10c-5c2371a0660e">|<img width="420" alt="스크린샷 2024-06-19 오전 8 36 12" src="https://github.com/primefaces/primevue/assets/37934668/dec2a116-c30b-4cbb-9b58-92436a5a1845">|

fix(Tooltip): apply color in bottom arrow

---

apps/showcase/doc/datatable/filter/BasicFilterDoc.vue

docs(BasicFilterDoc.vue) Remove unused format functions

---

packages/primevue/src/datepicker/DatePicker.vue

- fix #5886 
- To resolve this, the condition for highlighting months has been modified.

fix(DatePicker): highlight range of month in monthMode

---

packages/primevue/src/datepicker/DatePicker.vue

- fix #5883
- To resolve this, the condition for highlighting years has been modified.

fix(DatePicker): highlight range of year in yearMode

---

packages/themes/src/presets/aura/chip/index.js
packages/themes/src/presets/lara/chip/index.js
packages/themes/src/presets/nora/chip/index.js

fix typo in three preset themes (chip/index.js)
fixes #6065 

fix: typo in theme presets (chip/index.js)

---

packages/primevue/src/autocomplete/AutoComplete.vue

Fix combination of multiple and dropdown

---

packages/primevue/src/treenode/TreeNode.d.ts

Forwardport of c05c42d from 3.53.0
See: https://github.com/primefaces/primevue/pull/5835

types: Make TreeNode.key required

---

packages/primevue/src/colorpicker/ColorPicker.d.ts
packages/primevue/src/colorpicker/ColorPicker.vue

fix: enable label click to open colorpicker

---

packages/primevue/src/select/Select.d.ts

It's an impact of changing the component name from "Dropdown" to "Select".

fix (docs): "Select also known as Select"

---

apps/showcase/doc/datepicker/BasicDoc.vue
apps/showcase/doc/datepicker/InlineDoc.vue

Change inline section to inform its usage. Also slight tweak of grammar in the basic section.

fix(docs): Update DatePicker inline and basic docs

---

packages/primevue/src/config/Config.d.ts

Fix - add buttongroup to PrimeVuePTOptions #6137 

---

packages/primevue/src/datepicker/style/DatePickerStyle.js

fix: https://github.com/primefaces/primevue/issues/6120

fix: month selection highlighting problem in range mode

---

packages/primevue/src/datepicker/DatePicker.vue

…he start date
fix: #6106, DatePicker: cannot type an end date that is the same as the start date

fix: #6106, DatePicker: cannot type an end date that is the same as the start date

---

packages/primevue/src/datepicker/DatePicker.vue

Make selections based on attributes not classes

Fix datepicker unstyled - https://github.com/primefaces/primevue/issues/6147

---

packages/primevue/src/datepicker/DatePicker.vue

For issue https://github.com/primefaces/primevue/issues/5870

fix: add @keydown emit event in DatePicker component

---

pnpm-lock.yaml

fix: prevent icon display when inline property is set

---

packages/primevue/src/inputotp/InputOtp.vue

[Issue](https://github.com/primefaces/primevue/issues/5386#issue-2173522392)
please check this PR.

fix: InputOtp - [IntegerOnly] make enable Tab, Enter Key down

---

apps/showcase/doc/dataview/LayoutDoc.vue

Fix issue #6242 - Syntax error in docs example

---

packages/primevue/src/config/Config.d.ts

fix: Add 'iconfield' to PrimeVuePTOptions

---

packages/primevue/src/inputotp/InputOtp.vue

[Issue](https://github.com/primefaces/primevue/issues/5386#issue-2173522392)
follow-up to https://github.com/primefaces/primevue/pull/6172

fix: InputOtp - allow NumpadEnter event

---

packages/primevue/src/select/Select.vue

Fixed issue where the select focus was lost when an option was selected with enter key while autoFilterFocus was true

---

packages/primevue/src/iconfield/IconField.d.ts

Update [Live Demo] urls

---

apps/showcase/doc/galleria/ResponsiveDoc.vue

fix: removed incorrect duplicate template
Page with error: https://primevue.org/galleria/#responsive

removed incorrect duplicate template in code sample

---

packages/primevue/src/drawer/Drawer.vue

Fix nested drawer when dissmissable value change #6262 on v4.0.5

Fix issue #6262 - Click outside only when not modal for v4.0.5

---

apps/showcase/doc/tree/selection/CheckboxDoc.vue
apps/showcase/doc/tree/selection/SingleDoc.vue

Fix #6390: Updated `Tree` example code of document

---

packages/primevue/src/drawer/Drawer.d.ts

fix(docs): emit options of drawer component description error

---

components/lib/config/PrimeVue.d.ts
components/lib/confirmationservice/ConfirmationService.d.ts
components/lib/dialogservice/DialogService.d.ts
components/lib/toastservice/ToastService.d.ts

Just a backport of https://github.com/primefaces/primevue/pull/6207
This is my first time contributing to an open source project, so sorry if I did something wrong.
Augment vue types instead of 'vue/types/vue' and '@vue/runtime-core' to fix incompatibility with other libraries caused by the current augmentation behavior
Fixes: https://github.com/primefaces/primevue/issues/6199

 fix(v3): global vue type augmentation

---

components/lib/calendar/Calendar.vue

- apply this PR to v3 
(https://github.com/primefaces/primevue/pull/5884, 
https://github.com/primefaces/primevue/pull/5986)
https://github.com/primefaces/primevue/assets/37934668/ac48a279-49b8-4970-920b-a8fc3ad488bf

fix(Calendar): highlight range of year in YearMode

---

components/lib/calendar/Calendar.vue

- apply this PR to v3 (https://github.com/primefaces/primevue/pull/5887)
https://github.com/primefaces/primevue/assets/37934668/8d8cf9c0-4284-46f7-8248-e03ab05cf4ba

fix(Calendar): highlight range of month in MonthMode

---

packages/primevue/src/datepicker/DatePicker.vue

fixes #6543
I also fixed the incorrect documentation part about this slot prop. The method doesn't accept any parameter.

fixes #6543 (missing slot prop: toggleCallback)

---

packages/primevue/src/checkbox/Checkbox.d.ts

fix(Checkbox): Added "update:indeterminate" emit.

---

packages/primevue/src/multiselect/MultiSelect.spec.js

test(multi-select): update unit tests

---

packages/primevue/src/datepicker/DatePicker.vue

fix(date-picker): prevent events from bubbling when overlay is clicked

---

packages/primevue/src/inputnumber/InputNumber.vue

Defect Fix: Not working InputNumber on Android devices.
(https://github.com/primefaces/primevue/issues/6766)

fix: InputNumber does not work on Android devices fix

---

packages/primevue/src/colorpicker/ColorPicker.vue

fix: prevent text cursor and typing in colorpicker

---

packages/primevue/src/toggleswitch/style/ToggleSwitchStyle.js

fix (ToggleSwitch): Fixed #6859

---

packages/primevue/src/virtualscroller/VirtualScroller.vue

#6776 fix: Virtual scroller: step prop in delay mode breaks the component

---

packages/primevue/src/select/style/SelectStyle.js

Fix #6896. Select: fluid doesnt apply properly

---

packages/primevue/src/fileupload/FileUpload.vue

Add isFileLimitExceeded before file is pushed in FileUpload

---

packages/primevue/src/treetable/TreeTableRow.vue

fix(TreeTable): Row selected on click at node toggle icon

---

apps/showcase/pages/textarea/index.vue

Deduplicated the IftaLabel section in the textarea docs

Deduplicated a section

---

packages/primevue/src/speeddial/SpeedDial.d.ts

fix: rename 'visible' to 'd_visible' in SpeedDialState interface

---

packages/primevue/src/tree/Tree.spec.js
packages/primevue/src/tree/Tree.vue

https://github.com/primefaces/primevue/issues/6962

fix: missing last typed letter on filter tree event

---

packages/primevue/src/timeline/Timeline.d.ts

fix(timeline): add count property to TimelineContext

---

packages/primevue/src/virtualscroller/VirtualScroller.vue

Fix Issue #6986

---

packages/primevue/src/select/Select.vue

fix: #7026, Select: Editable Dropdown search not working as expected

fix: #7026, Select: Editable Dropdown search not working as expected

---

packages/primevue/src/datepicker/DatePicker.vue
packages/primevue/src/select/Select.vue

Fix https://github.com/primefaces/primevue/issues/7104

fix(date-picker-and-select): realign after orientation change

---

packages/primevue/src/multiselect/MultiSelect.d.ts

Fix https://github.com/primefaces/primevue/issues/7121

docs(multi-select): add missing removeCallback prop on chip slot

---

packages/primevue/src/multiselect/MultiSelect.d.ts

Fix https://github.com/primefaces/primevue/issues/7124

fix(multi-select): add exposed methods to types

---

packages/primevue/src/datatable/ColumnFilter.vue
packages/primevue/src/multiselect/MultiSelect.d.ts
packages/primevue/src/select/Select.d.ts

Fix https://github.com/primefaces/primevue/issues/7126

fix(select): add exposed methods to types

---

packages/forms/src/formfield/FormField.d.ts

fix(forms): add name attribute to FormFieldProps

---

packages/primevue/src/select/Select.vue

fix: filter input reference check on overlay close

---

packages/primevue/src/select/Select.d.ts

fix(select): fix the missing of the pass-though prop named `dropdownIcon`

---

packages/primevue/src/confirmdialog/ConfirmDialog.d.ts

fix(confirmdialog): fix the missing of the pass-though prop named `mask`

---

packages/primevue/src/virtualscroller/VirtualScroller.vue

Add a parameter and skip using it

fix(VirtualScroller): Typo - missing calculations for grid column

---

apps/showcase/components/layout/AppDesigner.vue
apps/showcase/components/layout/designer/create/DesignCreateTheme.vue
apps/showcase/components/layout/designer/dashboard/DesignDashboard.vue
apps/showcase/components/layout/designer/editor/settings/DesignSettings.vue
apps/showcase/nuxt.config.js
apps/showcase/plugins/app-state.js

Redo CSRF part for Designer

---

apps/showcase/components/layout/AppDesigner.vue
apps/showcase/components/layout/designer/create/DesignCreateTheme.vue
apps/showcase/components/layout/designer/dashboard/DesignDashboard.vue
apps/showcase/components/layout/designer/editor/settings/DesignSettings.vue
apps/showcase/nuxt.config.js

Update variable name

---

apps/showcase/assets/styles/layout/_core.scss
apps/showcase/assets/styles/layout/_designer.scss
apps/showcase/assets/styles/layout/variables/main/_dark.scss
apps/showcase/assets/styles/layout/variables/main/_light.scss
apps/showcase/components/layout/AppConfigurator.vue
apps/showcase/components/layout/AppDesigner.vue
apps/showcase/components/layout/designer/create/DesignCreateTheme.vue
apps/showcase/components/layout/designer/dashboard/DesignDashboard.vue
apps/showcase/components/layout/designer/editor/DesignColorPalette.vue
apps/showcase/components/layout/designer/editor/DesignTokenField.vue
apps/showcase/components/layout/designer/editor/custom/DesignCustomTokens.vue
apps/showcase/components/layout/designer/editor/primitive/DesignColors.vue
apps/showcase/components/layout/designer/editor/semantic/DesignGeneral.vue
apps/showcase/components/layout/designer/editor/semantic/colorscheme/DesignCSCommon.vue
apps/showcase/nuxt.config.js

Designer Updates

---

packages/primevue/src/inputnumber/InputNumber.vue

Reporting an issue fixed in V3 but present in V4 : https://github.com/primefaces/primevue/pull/6506

feat(InputNumber): French keyboard decimal support

---

packages/primevue/src/select/Select.vue

Select: Style error when resize window. #7360 fix

fix: #7360 - Select: style error when resize window

---

packages/primevue/src/galleria/GalleriaItem.vue

fix: permanently disabled item navigators in the gallery component (#7321 )

fix: galleria item navigators disable state

---

packages/primevue/src/select/Select.vue

fix: add name attribute in select

---

packages/primevue/src/datepicker/DatePicker.vue

Fixes issue [#7397](https://github.com/primefaces/primevue/issues/7397)

Fix DatePicker parsing ISO string

---

packages/primevue/src/dynamicdialog/DynamicDialog.vue

I think that binding events with v-bind does not work after some version of Vue. Using v-on fixes the issue.
Fix https://github.com/primefaces/primevue/issues/7429

fix(dynamic-dialog): use v-on instead of v-bind for emits

---

packages/core/src/index.d.ts
packages/primevue/src/datatable/DataTable.d.ts

Infer the DataTable generic type from the value prop

---

packages/primevue/src/tooltip/Tooltip.js

Fixes https://github.com/primefaces/primevue/issues/5856

fix(tooltip): fix memory leak by storing bound event handler references

---

packages/primevue/src/tablist/TabList.vue

fixes(TabList): Do not update inkbar if element doesn't exists

---

packages/primevue/src/panelmenu/PanelMenuList.vue

fix(primevue): fix the issue that `panel menu` cannot render the correct `SSR dom` that contains nested active list items

---

packages/primevue/src/galleria/Galleria.vue

chore(primevue): enable to focus back after `galleria` component hiding

---

packages/primevue/src/datatable/DataTable.vue

Add type guards to DataTable restoreState to prevent errors & state corruption

---

packages/primevue/src/keyfilter/KeyFilter.js

Fix #7463 
- Fixed `onKeydown` method to insert the key at the cursor position rather than appending at the end
- Updated the `onPaste` method to follow the same pattern, inserting clipboard content at cursor position

Refactor KeyFilter to improve value validation during key and paste events

---

apps/showcase/components/demo/DeferredDemo.vue
packages/core/src/basedirective/BaseDirective.js
packages/core/src/usestyle/UseStyle.js
packages/primevue/src/datatable/DataTable.vue

Fix #7448 
I thought this PR doesn't fix all the memory leaks.

fix(primevue): try to fix the memory leak of the `datatable` component

---

packages/forms/src/form/Form.d.ts

fix(form): make FormSubmitEvent generic for better type safety

---

packages/primevue/src/datepicker/DatePicker.vue
packages/primevue/src/select/Select.vue

Fix for https://github.com/primefaces/primevue/issues/7161

fix: DatePicker/Select fix outsideClickListener inside web components

---

packages/primevue/src/tab/Tab.vue

fix(primevue): fix the issue that cannot correctly get the last `tab` item

---

packages/primevue/src/cascadeselect/CascadeSelectSub.vue

Fixed https://github.com/primefaces/primevue/issues/5534

Added Function to CascadeSelectSub props to remove type check warning

---

apps/volt/volt/Paginator.vue

Fix ref import missing for Paginator.vue

---

packages/primevue/src/image/Image.vue

Fixes https://github.com/primefaces/primevue/issues/7652

fix Image custom preview icon

---

apps/showcase/doc/dynamicdialog/EventsDoc.vue

fix: DynamicDialog 'Events' example

---

apps/volt/volt/Select.vue

Fix https://github.com/primefaces/primevue/issues/7586

fix: add onclick handler to volt `select` component clear icon

---

packages/primevue/src/datatable/ColumnFilter.vue

fix: typos in columnfilter

---

packages/primevue/src/tooltip/Tooltip.js

Make sure no tooltip element will be created after tooltip is unmounted

---

packages/core/src/baseeditableholder/BaseEditableHolder.vue

https://github.com/primefaces/primevue/issues/7589

Fix falsy defaultValue in uncontrolled mode

---

packages/primevue/src/datepicker/DatePicker.vue

#7569 
Added the novalidate attribute to prevent the InputText inside DatePicker from being registered in the form.

fix(datepicker): Add novalidate attribute with value true

---

packages/primevue/src/accordioncontent/AccordionContent.vue
packages/primevue/src/accordionheader/AccordionHeader.vue

Fix AccordionHeader and AoccrdionContent computed id

---

packages/primevue/src/inputnumber/InputNumber.vue

fix: disable paste function on readonly mode

---

apps/showcase/doc/common/apidoc/index.json
packages/primevue/src/selectbutton/SelectButton.d.ts

issue: #7718 
Description: Add context property to SelectButtonPassThroughMethodOptions for type-safe access to active and disabled states. Updated types and docs.

fix(SelectButton): add context prop to SelectButton and doc

---

packages/primevue/src/datatable/DataTable.d.ts

fix groupRowsBy prop type error

---

apps/showcase/doc/passthrough/GlobalDoc.vue

docs: spelling and grammar fix

---

packages/primevue/src/scrollpanel/ScrollPanel.vue

Fix scrollBarY top attribute calculation

---

apps/showcase/doc/datatable/ContextMenuDoc.vue
apps/showcase/doc/treetable/ContextMenuDoc.vue

docs: fix typo in context menu doc

---

apps/showcase/doc/common/apidoc/index.json
packages/primevue/src/calendar/Calendar.d.ts
packages/primevue/src/datatable/DataTable.d.ts
packages/primevue/src/datepicker/DatePicker.d.ts

- fix https://github.com/primefaces/primevue/issues/7954

Fix typo at apidoc

---

packages/primevue/src/datepicker/DatePicker.vue

fix(datepicker): clear seconds when showSeconds is false

---

packages/primevue/src/inputnumber/InputNumber.vue

fix(InputNumber): fix decimal value on spin

---

apps/volt/doc/multiselect/DownloadDoc.vue

Incorrect command, was showing import instead of download of component

Update DownloadDoc.vue for MultiSelect component

---

packages/primevue/src/inputnumber/InputNumber.vue

Fiexed: InputNumber Component does not block composition input (IME - Korean, Japanese)

---

packages/primevue/src/treetable/TreeTable.vue

same fix as in #8061 but for TreeTable
fixes: #8064

fix(TreeTable): added missing data-p attributes

---

apps/showcase/doc/textarea/FloatLabelDoc.vue

docs: fix id attribute in textarea examples

---

packages/primevue/src/inputotp/InputOtp.vue

fix: enable single-field editing in OTP input

---

packages/primevue/src/confirmdialog/ConfirmDialog.d.ts
packages/primevue/src/confirmdialog/ConfirmDialog.vue

Fix ConfirmDialog container slot dragging issue (ref: #7893)

fix(ConfirmDialog): add drag functionality to container template

---

apps/showcase/doc/colorpicker/ControlledDoc.vue
apps/showcase/pages/colorpicker/index.vue
packages/primevue/src/colorpicker/ColorPicker.vue

Fix the issue missed in #7291
Before fix:
The hue handler did not move.
https://github.com/user-attachments/assets/4f358816-20ca-418c-8120-3c336d46f0ba
After fix:
https://github.com/user-attachments/assets/3e439465-b06a-4463-877d-70e559275677

Fix: uncontrolled behavior in ColorPicker component

---

packages/primevue/src/inputotp/InputOtp.vue

Same as described here: https://github.com/primefaces/primevue/pull/8095
, but applied to the InputOTP only, in order to fix a bug in Android browsers =)
#8095 , #8096

fix/refactor: rewrite event.code --> event.key for <InputOTP />
