src/components/menubar/Menubar.vue

There was an extra single quote in the class name in the Menubar component. This caused the CSS for this component to break.

Class fix for menubar

---

src/components/calendar/Calendar.vue

When clicking the today button in the calendar there was a broken reference to the event.

Fixed broken today button in the Calendar component

---

src/components/dialog/Dialog.vue
src/components/utils/DomHandler.js

When opening a closable dialog, the focus goes to the close button.
```html
<button aria-label="close" type="button"
class="p-dialog-titlebar-icon p-dialog-titlebar-close p-link">...</button>
```
This button should not be focused
**Note** : this is an attempt to fix this problem, may be there is a better way to do so ?

Fix closable dialog focus

---

src/components/editor/Editor.vue

Replaced 'import * as Quill' with 'import Quill' since Quill is expected
to be a constructor not an object.
Using, for example, Parceljs to bundle a project importing primevue/editor gave me the error `e is not a constructor`, after examining this in the debugger I found that `e` (the temporary name returned by the import) was actually some kind of module object instead of the expected function constructor, additionally the expected function constructor was store as `e.default` instead.

Updated Quill import so it works with current module standards

---

src/components/datatable/TableHeader.vue

The Component-Name was renamed from 'ColumnSlot' to 'DTColumnSlot' to match the name as it was registered.

BugFix: Renamed 'ColumnSlot' -> 'DTColumnSlot' in TableHeader

---

src/components/button/Button.vue

I've added a default `<slot>` inside `Button`, this enables us to pass in custom components. For example, if we'd like to use font-awesome icons instead of the built in primeicons:
```html
<Button>
<font-awesome icon="check" />
</Button>
```
Let me know if you'd like an example added to the documentation.

Button slot

---

src/components/progressbar/ProgressBar.vue
src/views/progressbar/ProgressBarDoc.vue

I've added a default slot to the ProgressBar component. This gives us more flexibility with the label.
Example usage:
```vue
<progress-bar :value="value">
Percent Complete: {{ value }}%
</progress-bar>
```

Added default slot to ProgressBar

---

src/components/password/Password.d.ts
src/components/password/Password.vue

The password weak level cannot be customized, so implemented a way that allow a customization using regular expressions.
Two new parameters are now accepted:
mediumCheckExpr (medium-check-expr) and strongCheckExpr (strong-check-expr).
The mediumCheckExpr has the following default value as string:
`"^(((?=.*[a-z])(?=.*[A-Z]))|((?=.*[a-z])(?=.*[0-9]))|((?=.*[A-Z])(?=.*[0-9])))(?=.{6,})"`
It means that medium level passwords are those that match with the following format:
- At least one lowercase
- At least one uppercase or one number
- Minimum 6 characters
The strongCheckExpr has the following default value as string:
`^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.{8,})`
It means that strong level passwords are those that match with the following format:
- At least one lowercase
- At least one …

Implemented custom password level check based on regular expressions

---

src/components/dialog/Dialog.d.ts
src/components/dialog/Dialog.vue
src/views/dialog/DialogDoc.vue

I've added support for `closeOnEscape` and `dismissableMask` to `Dialog`.
I selected the same default values as [PrimeReact Dialog](https://primefaces.org/primereact/showcase/#/dialog).
Resolves: #372

Added 'dismissableMask' and 'closeOnEscape' props to Dialog

---

src/views/terminal/TerminalDoc.vue

The TerminalService does not have $on, $off, and $emit properties. I believe this comes from the ts declaration, but in plain js, this produces an error. Even in the TerminalDemo.vue, the TerminalService uses the event listeners without the $ sign. This should be fixed, because its misleading.

TerminalDoc update

---

src/components/fileupload/FileUpload.vue

Using `:fileLimit` causes these errors [#610 ](https://github.com/primefaces/primevue/issues/610) and 
According to `Message` component, also `checkFileLimit()` fixed.

FileUpload fileLimit warns

---

src/views/toast/ToastDoc.vue

Importing from `primevue/useToast` causes this error:
`Module not found: Error: [CaseSensitivePathsPlugin] 'C:\...\node_modules\primevue\useToast.js' does not match the corresponding path on disk 'usetoast.js'.`
When I changed to `primevue/usetoast` it started to work 👍.

Fix import useToast in Composition API example.

---

src/components/selectbutton/SelectButton.vue

In non multiple SelectButton, when an option is clicked, the value never will be null.
Related to the issue [#494 ](https://github.com/primefaces/primevue/issues/494)

SelectButton click always makes an option is selected

---

src/components/panelmenu/PanelMenuSub.vue

`PanelMenu` component was ignoring `class` property of its model's items because of a typo. This PR solves that issue.

Fixed use of MenuModel's "class" property in PanelMenuSub

---

src/components/confirmationservice/ConfirmationService.d.ts
src/components/toastservice/ToastService.d.ts

Without this fix typescript throws this errors:
`Property '$confirm' does not exist on type 'App'.`
`Property '$toast' does not exist on type 'App'.`

Vue 3 + TS: fix for config.globalProperties services

---

src/components/config/PrimeVue.d.ts

vue 3 does not export a `PluginFunction` type. The `install` function should be of type `PluginInstallFunction`, but even that isn't exported. Instead we declare the type of the default export as `Plugin`.
See
https://github.com/vuejs/vue-next/blob/f0cf14bcc56c387372932e7d730f838ece17fe5f/packages/runtime-core/src/apiCreateApp.ts#L90-L96.
Fixes #1164.

Fix plugin type in config/PrimeVue.d.ts

---

src/components/carousel/Carousel.vue

When totalIndicators is below 0 (when the value prop is an empty array) and numScroll !== numVisible, a RangeError is thrown.
Fixes #1201.

Add conditional rendering to Carousel indicators

---

src/components/password/Password.vue

This was added as "toString" instead of "String", this this component breaks during development as it's typechecked

Fix incorrect type on inputClass

---

src/components/password/Password.vue

Three small fixes:
- className where "class" is correct
- a let that should be a const as the variable is never reassigned
- a superfluous % after a "0" CSS value

Linting fixes in Password.vue

---

src/components/overlaypanel/OverlayPanel.vue

When I try to highlight some text inside the overlay, if the cursor ends its run outside, the panel will be close.
I checked the code, and I found that "selfClick" property is used to avoid that, but I think It's attached to the wrong event.
I changed "click" event with "mousedown".

Fix: Prevent overlay closing if click start inside

---

src/components/overlaypanel/OverlayPanel.vue

Hi,
On this PR https://github.com/primefaces/primevue/pull/1361 the event used for checking if the click is inside the overlay was changed from @click to @mousedown
This caused the overlay to hide when clicking on a <label> tag within the overlay
In this PR, i'm adding a listener for the click event that calls onContentClick function
I tested this change locally and now both clicking on a label or trying to select text work both fine
Fixes https://github.com/primefaces/primevue/issues/1528
Re production of the bug https://codesandbox.io/s/wonderful-agnesi-020nn

[Fix] Prevent overlay from closing when clicking on a label inside

---

src/components/speeddial/SpeedDial.vue

this.bindDocumentClickListener() is called in beforeMount without case checking. update code to check props hideOnClickOutside before bind listener.

SpeedDial hideOnClickOutside not working

---

src/components/datatable/DataTable.d.ts

The DataTable.d.ts file is missing the 'expansion' field in the $slots class field.
This PR adds the missing field.
This PR resolves Issue #1629 

Add missing 'expansion' slot TypeScript definition to DataTable.d.ts

---

src/components/overlaypanel/OverlayPanel.vue

This PR adds the emits: ['show', 'hide'] to OverlayPanel component.
Without these vue will throw warnings in the console
Also in vue js docs, they encourage to add the emits
Also the IDE will benifit us developers when defining 'emits' because that will enable auto complete on the custom events as well

Add events emitted by OverlayPanel

---

src/components/confirmationservice/ConfirmationService.d.ts
src/components/toastservice/ToastService.d.ts

* `"vue": "^3.2.6"`
* `"vite": "^2.5.2"`
* `"vue-tsc": "^0.2.2"`
if using `vue-tsc --noEmit`, it not working with these error. 
```bash
node_modules/primevue/confirmationservice/ConfirmationService.d.ts:1:15 - error TS2305: Module '"vue"' has no exported member 'PluginFunction'.
import Vue, { PluginFunction } from 'vue';
~~~~~~~~~~~~~~
node_modules/primevue/toastservice/ToastService.d.ts:1:15 - error TS2305: Module '"vue"' has no exported member 'PluginFunction'.
import Vue, { PluginFunction } from 'vue';
~~~~~~~~~~~~~~
```

Fixed #1596 :  Typescript `Plugin` issue of `ConfirmationService.d.ts` and `ToastService.d.ts`

---

src/views/datatable/DataTableDoc.vue

Two closures are missing on "Filter Row" and "Filter Menu" section on docs

Fix DataTable Element Closure in Datatable Documentation

---

src/components/message/Message.vue
src/views/message/MessageDemo.vue
src/views/message/MessageDoc.vue

Added a prop "icon" to the Message.vue component.
This allows to set a custom icon for the Message.vue component.
Extended the documentation by the new prop.

add property "icon" to Message.vue to display a custom icon

---

src/components/chart/Chart.vue

Use deep watch on data prop to enable triggering watch for changes within structure otherwise the entire data object needs to be replaced to trigger watch

Update Chart.vue to trigger on any change to object data

---

src/components/datatable/DataTable.vue

When wrapping vue components, default slots get nested inside the slot's children array. So if you attempt to pass default slots down through multiple layers, they will be nested further. See link below. Currently, the DataTable component can only be wrapped once as the computed property for columns() only checks against the children array and is not recursive. If you attempt to wrap the components inside multiple layers, it does not work. Proposed is an update to the columns computed property to make it recursive. 
https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBHcmFuZFBhcmVudCBmcm9tICcuL0dyYW5kUGFyZW50LnZ1ZSc7XG5cblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPkdyZWF0R3JhbmRQYXJlbnQ8L2gxPlxuICA8R3JhbmRQYXJlbnQ+XG4gIFx0PHNwYW4+Q29sdW1uIDE8L3NwYW4+XG4gICAgPHNwYW4+Q29sdW1 …

Update DataTable.vue to make computed property columns() recursive

---

src/components/panelmenu/PanelMenu.vue

Items in the PanelMenu should have unique IDs. This PR fixes this by appending an items index to the id.
This also addresses issue #1791

Append index to ids

---

src/components/column/Column.vue

Fix for #2097
To match the Typescript types added in #1078 and not trigger Vue's "Invalid prop" warnings.

Add Function to Column prop field types

---

src/components/confirmationoptions/ConfirmationOptions.d.ts

Add missing "defaultFocus" attribute to ConfirmationOptions.d.ts

---

src/components/treetable/TreeTable.d.ts

Added missing selection mode for tree table in typescript type definition
Fixes #2148

Typescript - Add checkbox selection mode for tree table

---

src/components/toast/Toast.d.ts

**Toast**: add missing `'top-right'` `ToastPositionType` causing Typescript compilation errors

Toast: add missing 'top-right' ToastPositionType causing Typescript compilation errors

---

src/views/menubar/MenubarDoc.vue

On line 186 there is a class binding quotation mark typo inside the <a> tag on the router configuration example that leads to an error when used. Simply changed
:class="{'active-link': isActive, 'active-link-exact": isExactActive}
to
:class="{'active-link': isActive, 'active-link-exact': isExactActive}"
in the <a> tag.

Fixed class binding quotation mark typo on Menubar Docs

---

src/components/tooltip/Tooltip.js

Corresponding issue: [issue 1976](https://github.com/primefaces/primevue/issues/1976#issuecomment-1013784156)
The tooltip will adjust position if the configured position has no enough space, When the adjusted position still has no enough space, just keep it at the configured position.

bugfix/tooltip_wrong_position: fixed

---

src/components/fileupload/FileUpload.vue

We can't re-select a new file because the file list is not cleared after uploading when using Custom Uploader with basic mode.
ref: https://github.com/primefaces/primevue/issues/1723
```vue
<FileUpload mode="basic" name="demo[]" :customUpload="true" @uploader="myUploader" />
```
```js
myUploader(event) {
//event.files == files to upload
}
```
In case not using Custom Uploader, it clear file list after upload.
https://github.com/primefaces/primevue/blob/a48fcc34d404c61194b97c0df8f5b8c0273aabb2/src/components/fileupload/FileUpload.vue#L240
How about this patch?

Fixed #1723 - Clear file list after upload

---

src/components/datatable/RowCheckbox.vue

To prevent clicks from propagating through to the row and triggering a row select/unselect event which undoes the effect.
Fixes #2259

Add stop modifier to RowCheckbox click event

---

src/components/config/PrimeVue.d.ts

fix global prop type definition in Vue 3

---

src/components/dataview/DataView.vue

DataView is missing :key in the main v-for which return odd states when pagination happens but results are contains the same tags but just changes some properties. This gets solved once the :key is there as a Vue understands is a new node.
This issue is a no brainer as v-for in general should use :key. You can see TableBody from DataTable makes use of :key.

Adds :key to DataView v-for

---

src/components/carousel/Carousel.vue

Fix #2516: Carousel less items than allocated slots
see https://github.com/primefaces/primefaces/issues/8265 for original bug and issue

Fix #2516: Carousel less items than allocated slots

---

src/components/image/Image.vue

This adds an extra function to pass through error event handling for images. This way it is possible to set a fallback image for example.

Add on error for images

---

src/views/datatable/DataTableDoc.vue

With label and value as described
Simple fix for invalid config object

Documentation quickfix: filterMatchModeOptions: Use valid object

---

src/components/timeline/Timeline.vue

Currently, style overrides to the timeline connector component happen globally at the timeline component level.  It is not an uncommon use case to require dynamic style overrides across multiple connectors for a given timeline instance. This can be achieved (as is being done with the `marker` and `content` named slot) by binding the `item` property to the `connector` named slot. This enables the following type of customization to connectors for a given timeline.
```vue
<template #connector="slotProps">
<div
class="p-timeline-event-connector"
:style="{ width: '4px', backgroundColor: slotProps.item.color }"
></div>
</template>
```
Unless there is a strong reason to not support this (can't see what that reason would be) I think this would be a really useful addition to the component!

feat: bind event item to timeline custom connector slot

---

src/components/slider/Slider.vue

When slider was in range mode, incrementing or decrementing the first handle messed up the model value.

Issue 2836: Fixed broken keyboard navigation

---

src/components/autocomplete/AutoComplete.d.ts

typo: changed "AutoCompletenOptionLabelType" to "AutoCompleteOptionLabelType" (removed extra "n")
Current compilation error: 
node_modules/primevue/autocomplete/AutoComplete.d.ts:95:24 - error TS2552: Cannot find name 'AutoCompletenOptionLabelType'. Did you mean 'AutoCompleteOptionLabelType'?
95     optionGroupLabel?: AutoCompletenOptionLabelType;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error in node_modules/primevue/autocomplete/AutoComplete.d.ts:95
Fixes #2866

fixed typo in AutoComplete.d.ts: AutoCompletenOptionLabelType -> AutoCompleteOptionLabelType with no extra "n"

---

src/views/tieredmenu/TieredMenuDoc.vue

There should be a double quotes end of the :class like that:
:class="{'active-link': isActive, 'active-link-exact': isExactActive}"

Missing double quotes

---

README.md
src/views/setup/Setup.vue

Fixes incorrect Nuxt3 config in the docs/readme. [Reference from starter template](https://github.com/primefaces/primevue-quickstart-nuxt3/blob/main/nuxt.config.js#L8-L10).

docs: fix nuxt config setup

---

src/components/calendar/Calendar.vue

In Calendar component, `readonly` prop is not working as expected since `manualInput` prop is set to readonly attribute instead.
Currently, when `readonly` prop is set true, input still accepts new input.
```
<Calendar v-model="value" :readonly="true" />
```
The issue is described here https://github.com/primefaces/primevue/issues/125
The repo for readonly bug is here https://github.com/nagisaando/primevue-calendar-readonly-error

set readonly prop to readonly attribute

---

api-generator/components/chips.js
src/components/chips/Chips.d.ts
src/components/chips/Chips.spec.js
src/components/chips/Chips.vue
src/views/chips/ChipsDoc.vue

Add custom icons support for the Chips component

---

src/components/splitter/Splitter.vue
src/views/splitter/SplitterDoc.vue

This just adds a 'resizestart' emit event from the existing onResizeStart function.
Resolves:
https://github.com/primefaces/primevue/issues/3203

Add 'resizestart' emit event when splitter is resized

---

api-generator/components/sidebar.js
src/components/sidebar/Sidebar.d.ts
src/components/sidebar/Sidebar.vue
src/views/sidebar/SidebarDoc.vue

Sidebar accessibility completed

---

src/views/timeline/TimelineDoc.vue

Improve Timeline Implementation for Accessibility

---

pages/accessibility/index.vue

The explanation talks about using a div instead of a button. Instead it uses a button (correctly)... but the example should be the 'bad' usage
```
On the other hand, a fancy css based button using a div has no keyboard or screen reader support.
```

Fixed the example code to match description

---

components/breadcrumb/Breadcrumb.vue

Breadcrumb: separator fix for home prop null cases

---

pages/locale/index.vue

I'm not quite sure what l7n could stand for, but l10n is the correct abbreviation of localization, what is also mentioned above.

Changes l7n to l10n

---

components/datatable/DataTable.vue
components/utils/ObjectUtils.js

This fixes #3443.
I did not update the Reorder demo, but if you add `:paginator="true" :rows="5"` to it you can confirm the issue and subsequent fix. Also tested on the existing Reorder demo without pagination and it works there as well.

Fix #3443: Datatable: RowReorder fails in case of pagination on page other than first & last

---

components/selectbutton/SelectButton.vue

Fixed an error, that cause the "unselectable" prop behaviour to be the inverse of the expected. This is a fix for

Fixes error in unselectable behaviour in SelectButton

---

doc/theming/ScaleDoc.vue

docs: fix theme overview scale typo

---

components/lib/dropdown/Dropdown.vue
components/lib/multiselect/MultiSelect.vue

Before this change, filtering with `optionGroupLabel`, etc, would assume that `optionGroupChildren` is `items`, and so when it was set to something else, `group.items` would be `undefined` and `(undefined).filter(...)` would cause an error.
resolves https://github.com/primefaces/primevue/issues/3807
**Please be sure to test this for yourself as you'd have better knowledge about filterservice!**

fix: visibleOptions respecting optionGroupChildren

---

components/lib/dropdown/Dropdown.vue

Dropdown does not show correct styling if using a falsey value such as `false` or `0`.
https://github.com/primefaces/primevue/issues/3891

Fix: Support non-empty values

---

components/lib/datatable/DataTable.vue

When a `DataTable` does not use a custom `ContextMenu`, it still clears the user's selection.
A demonstration of the bug:
[data-table-bug.webm](https://user-images.githubusercontent.com/10552683/236423826-8d42fce6-3a99-43a3-b746-b251ec4c818e.webm)
And with this proposed fix:
[data-table-fix.webm](https://user-images.githubusercontent.com/10552683/236423870-a51eb5c0-bda2-408f-bb35-0746f54c7ca0.webm)
All custom events will work as before, but users might have to manually call the selection clear and focus methods from their own `row-contextmenu` listeners, which is less restrictive, but maybe a BC break.
closes #3927

fix: DataTable: Selection and focus loss when no custom ContextMenu is defined

---

components/lib/steps/Steps.vue

In case of long labels, steps component goes beyond the frame.
It is clearly visible on mobile devices.
This is fixed by adding text-overflow: ellipsis to the label.
Here you can find a sandbox with the fix applied: https://codesandbox.io/s/dreamy-tree-8xequk?file=/src/Steps.vue
Fix #3631

fix(Steps): add text-overflow ellipsis

---

doc/autocomplete/DisabledDoc.vue

This PR fixes the description of `autocomplete/disabled` in docs. I didn't create an issue to associate with it because it was simple.

fix(docs): autocomplete disabled

---

components/lib/picklist/PickList.d.ts

The **showSourceControls** and **showTargetControls** properties have a default value of true in the codebase (https://github.com/primefaces/primevue/blob/master/components/lib/picklist/BasePickList.vue), while the docs incorrectly says the default value is false. (https://github.com/primefaces/primevue/blob/master/components/lib/picklist/PickList.d.ts)

fix (docs): PickList documentation properties default value fix

---

components/lib/tooltip/Tooltip.js

Bugfix: prevent tooltip to appear if the binded element is removed from DOM

---

components/lib/focustrap/FocusTrap.js

According to [MDN][1] `classList` is a read-only property. To properly write to it you use its [`value`][2] property (`DOMTokenList#value`) 
[1]: https://developer.mozilla.org/en-US/docs/Web/API/Element/classList
[2]: https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/value
#4015

Don't write directly to classList in FocusTrap.js

---

components/lib/inputnumber/InputNumber.vue

Currently if you enter a negative number in the InputNumber field (with formatting set to a currency with a suffix), the input becomes doubled (f.e. if you type -1, it becomes -11). This is because there is a missing check if decimalCharIndex is valid or not. 
Unfortunately I did not find a solution for writing a test, that covers this bug, because this relies on the keydown event handling of input fields (which vue-test-utils does not support at the time). If you have an idea how to fix this, please let me know, I am happy to write a test for this issue.
Fix #3382

InputNumber: fix formatting of currencies with suffix

---

components/lib/config/PrimeVue.d.ts

[TypeScript: changeTheme is not declared](https://github.com/primefaces/primevue/issues/4118)
Adds `changeTheme` function definition to PrimeVue config type.

Add changeTheme to PrimeVue TS interface

---

components/lib/multiselect/MultiSelect.vue

v-show added for checkIcons

---

components/lib/inputswitch/InputSwitch.d.ts

InputSwitch passthrough hotfix

---

components/lib/dialog/Dialog.vue

Fixes #4251  
This issue linked to the fixes for PrimeNg and PrimeReact
-  https://github.com/primefaces/primeng/issues/13493 - Prime Ng
-  https://github.com/primefaces/primereact/pull/4760 - Prime React

fix: fix the unexpected behavior of the ConfirmDialog popup

---

components/lib/password/Password.vue

Password component would not be completely disabled using disabled prop because disabled wouldn't be passed to primevue/inputtext.
As a result if the field was disabled while it was focused user could type and user can also still navigate with tab and write in the disabled field.
559/c76bb7bb-bbcd-4401-be3e-5ca6bb3764e7)

fixed disabled prop on Password component

---

components/lib/datatable/DataTable.vue

Big performance gain using Int.Collator. It is not recommended to use localeCompare against large arrays.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare
#4007

use Intl.Collator instead of localeCompare to boost sort time

---

components/lib/basecomponent/BaseComponent.vue

Fix #2238 
-  On hover to outline button groups, button redundant right border removed. Mentioned in https://github.com/primefaces/primevue/issues/2238

fix: button border right bug on hover

---

components/lib/datatable/TableBody.vue

As detailed in #3858 and #3896, row grouping is not working with pagination.  This is due to the [`getRowIndex` function](https://github.com/primefaces/primevue/blob/511db538de02f77abc916110a6134012b24708f5/components/lib/datatable/TableBody.vue#L331-L335) adding `this.first` to the row index.  `getRowIndex` is called by as part of the [`shouldRenderRowGroupHeader` call](https://github.com/primefaces/primevue/blob/511db538de02f77abc916110a6134012b24708f5/components/lib/datatable/TableBody.vue#L6).
The problem is that when pagination is enabled, the `DataTable` competent slices the data passed to `TableBody` in the [`dataToRender` function](https://github.com/primefaces/primevue/blob/511db538de02f77abc916110a6134012b24708f5/components/lib/datatable/DataTable.vue#L2161-L2171), so the size …

#3858 #3896 - fix row grouping with pagination

---

components/lib/dropdown/Dropdown.spec.js
components/lib/dropdown/Dropdown.vue

Add key binding for clearing the input of the Dropdown in the showClear mode.
This is a proposal of a possible implementation of the requested feature. Feel free to share your thoughts or improvements!.
Fix  #3834

Dropdown: add clear input key binding

---

components/lib/datatable/DataTable.vue

Helps fix https://github.com/primefaces/primevue/issues/4007
This PR does 2 main things to help improve filtering and sorting performance for DataTables:
- Within the `sortSingle` function, performing calls to `resolveFieldData(data1, this.d_sortField)` only once for each item in the dataset, and using a `Map` for later lookups.
- Within the `filter` function, only run filters whose `value` is not `null`.

Improve datatable performance

---

components/lib/basecomponent/BaseComponent.vue

https://github.com/primefaces/primevue/issues/4360
This PR fixes an issue with `unstyled` being accessed on an `undefined` config object, causing tests to fail.

Issue 4360 - Fixed unstyled config for BaseComponent

---

components/lib/datatable/DataTable.vue

Fixes #4337
Following [https://v3-migration.vuejs.org/breaking-changes/watch.html#overview](https://v3-migration.vuejs.org/breaking-changes/watch.html#overview) and making the prop deep watched.
Please review if that solution is okay for you guys !

Fixed #4337 - DataTable: editingRows is not reactive

---

components/lib/autocomplete/AutoComplete.spec.js
components/lib/autocomplete/AutoComplete.vue

This pr fixes the bug from issue #3669 (Fix #3669).
The problem was, that the overlay was going to be hidden if the search input did not match any suggestions and therefor the empty message was not shown.
I also added some tests that should prevent this bug from happening again.
As this is my first pull request to this repository, I am happy to refactor to your needs and I hope I submitted everything by your satisfaction. If not or if I missed some of your protocol, just let me know!
During the debugging, I also found a further bug (#3865)

AutoComplete: show overlay if there are no suggestions

---

components/lib/datatable/DataTable.vue
components/lib/datatable/TableBody.vue

Fixes #4120
Uses the self modifier on keydown event to catch events emitted on the <tr> tag only. This allows keydown events to be handled lower in the DOM tree and still allows row selection with keyboard.
Note that input by inputing a space or enter character in an Input field, it does not select the row where the Input belongs to.

Fixed #4120 - DataTable: Selection and Row/Cell editing : Cannot input space character

---

components/lib/config/PrimeVue.d.ts
components/lib/config/PrimeVue.js
components/lib/fileupload/FileContent.vue
components/lib/fileupload/FileUpload.vue
doc/common/apidoc/index.json
doc/configuration/locale/LocaleApiDoc.vue
doc/fileupload/TemplateDoc.vue

Fix #4376
Following the indications of @mertsincan in this comment: https://github.com/primefaces/primeng/pull/13400#issuecomment-1697703103,
I added **fileSizeTypes** and updated the docs.
Also I refactored the formatSize function as PrimeNG and PrimeReact projects.

FileUpload: Added fileSizeTypes 

---

components/lib/utils/ObjectUtils.js

Object.keys can get expensive when called a lot of times. Adding a try catch for the quickest and probably highest use case can lead to big performance gains. Related to #4296 but for overall performance
I don't have the time to run through the other scenarios, but I think just doing try catch for each scenario would be faster than the call to Object.keys and isFunction. It would look something like.
```
let value = null;
try {
value = data[field];
if (value)
return value;
}
catch { }
try {
value = field(data);
if (value)
return value;
}
catch { }
try {
let fields = field.split('.');
let nestedValue = data;
for (var i = 0, len = fields.length; i < len; ++i) {
if (nestedValue == null) {
return null;
}
nestedValue = nestedValue[fields[i]];
}
return nestedValue;
}
catch { }
return null;
``` …

Performance update for resolveFieldData

---

components/lib/datatable/TableBody.vue

Complete initiated work on https://github.com/primefaces/primevue/pull/2595 and #2589

Fix #2589 vue.js warning for DataTable with dataKey as a function

---

components/lib/splitbutton/SplitButton.vue

The SplitButton component of PrimeVue was missing a preventDefault() call when clicking on the button that opens the dropdown menu. This caused unexpected behavior when interacting with the dropdown menu. The issue has been resolved by adding the preventDefault() on the click event, ensuring smooth and expected functionality.
Fixes #4223"

Fix: Add preventDefault on SplitButton click event

---

components/lib/tree/Tree.spec.js
components/lib/tree/TreeNode.vue

Currently when you use a input within the TreeNode content, some keys (f.e. space key) do not work, because the event listener of the TreeNode uses them for navigating in the tree view. 
I stopped the event propagation from the content to the TreeNode, so that the elements in the content work fine, but also the navigation in the Tree is not affected.
If you have any questions regarding this PR, feel free to ask!
Fix  #3831

fix(TreeNode): stop keydown event propagation from content

---

README.md

Fix #4461. Add Discussions badge to the README for awareness and potential SEO.
Badge in action can be viewed at: https://github.com/FlipWarthog/primevue/tree/discussions-badge

Fix #4461: Add Discussions badge

---

components/lib/passthrough/tailwind/index.js

Tree leaf toggler must have "visibility: hidden" instead of "display: none"

fix: tree toggler leaf class

---

components/lib/panelmenu/PanelMenuList.vue

Fixed #4522 - Add extra check for separator item

---

api-generator/components/editor.js
src/components/editor/Editor.d.ts
src/components/editor/Editor.vue

Implements the feature requested in #4450, thus bringing Editor in primevue v2 on par with v3.

Add `modules` property to Editor

---

components/lib/basecomponent/style/BaseComponentStyle.js

Applies same fix for the same issue implemented to "primeng" in 2018: https://github.com/primefaces/primeng/pull/5473/commits/d2abf21fb9c63862f28b67ce581274464c01986d
Issue: https://github.com/primefaces/primevue/issues/4533

Fixes InputText component "float" label styles for webkit based auto-fill

---

components/lib/splitter/Splitter.d.ts
components/lib/splitter/Splitter.vue
doc/common/apidoc/index.json
doc/splitter/HorizontalDoc.vue

Add resizing event to splitter component
```html
<Splitter style="height: 300px" class="mb-5" @resizing="console.log">
<SplitterPanel class="flex align-items-center justify-content-center"> Panel 1 </SplitterPanel>
<SplitterPanel class="flex align-items-center justify-content-center"> Panel 2 </SplitterPanel>
</Splitter>
```

Add resize event to splitter

---

components/lib/passthrough/tailwind/index.js

The style of the splitter-panel component is written in the wrong place.

Fix TailwindCSS theme for splitter component

---

components/lib/api/FilterService.js

This is an identical fix that was used in primereact to allow filtering plain string sources in filter.
https://github.com/primefaces/primevue/issues/4071

issue #4071 fix

---

components/lib/toast/Toast.d.ts

Fix #4568: Adds type support to allow access to message props in Toasts by adding the message property to the ToastProps type.

Fix #4568: Add missing message property on ToastProps type

---

api-generator/components/selectbutton.js
components/lib/selectbutton/BaseSelectButton.vue
components/lib/selectbutton/SelectButton.d.ts
components/lib/selectbutton/SelectButton.vue
doc/common/apidoc/index.json

In #3610, the meaning of the `unselectable` property on SelectButton was reversed from "able to unselect" to "**un**able to unselect". Because [the documentation](https://primevue.org/selectbutton/#api.selectbutton.props.unselectable) was not updated accordingly, the property currently behaves exactly opposite to how it's described. 
In #3708 and #3973, there was significant disagreement as to what the property should mean. I would agree with those arguing that the textbook meaning of "unselectable" would be that you are able to unselect. However, the name clearly causes some confusion. 
In this PR, I've therefore deprecated the `unselectable` property in favour of the `allowEmpty` property, to avoid further breaking changes. This naming is much less ambigious, and matches the one already …

Fix ambigious clearing behaviour on SelectButton

---

components/lib/orderlist/OrderList.vue

Linked issue https://github.com/primefaces/primevue/issues/4581

Fix #4581 - Adding back missing 'moveUpButtonProps' in OrderList

---

CHANGELOG.md
README.md
components/lib/utils/ObjectUtils.js

`kebap` was used in several places throughout the repo. The correct usage is `kebab` as seen here: https://developer.mozilla.org/en-US/docs/Glossary/Kebab_case
https://github.com/primefaces/primevue/issues/4594

Fixed kebab typo

---

doc/menu/RouterDoc.vue

When we use the Vue router as shown in the docs, the page is doing a full reload instead of navigating directly to a given route. This leads to state loss.

fix: navigate to page instead of full page load

---

components/lib/picklist/PickList.spec.js
components/lib/picklist/PickList.vue

Fix: #4072 
- Prevent Double click add item twice, only unique

fix:4072 - Picklist: Unexpected behavior on double click while holding control

---

components/lib/button/Button.spec.js
components/lib/rating/Rating.spec.js
components/lib/splitbutton/SplitButton.vue
vitest.config.js

Fix #4599 - PR Checker build failing
Creating as a draft to test the workflows

Fix #4599 - PR Checker build failing

---

layouts/AppTopBar.vue

Fix #4605: Use DocSearch in non prod env too
Copying the logic from https://github.com/primefaces/primereact/pull/4213

Fix #4605: Use DocSearch in non prod env too

---

components/lib/tooltip/Tooltip.d.ts
components/lib/tooltip/Tooltip.js
components/lib/tooltip/style/TooltipStyle.js
doc/tooltip/AutoHideDoc.vue
pages/tooltip/index.vue

#3568
Add autoHide feature, with documentation

Tooltip: autoHide

---

components/lib/splitter/Splitter.vue

Fix #4652 - Splitter: minSize broken
Ported from PrimeReact.

Fix #4652 - Splitter: minSize broken

---

components/lib/panelmenu/PanelMenu.vue

Fix #4671 - PanelMenu: Error when using #item slot

Fix #4671 - PanelMenu: Error when using #item slot

---

components/lib/carousel/Carousel.vue

Fixes an issue where updating the `page` attribute from outside the `Carousel` component wasn't updating the items visible.
Closes #4684

fix(carousel): page attribute not updating shown items

---

components/lib/scrollpanel/ScrollPanel.vue

Fix #4689 - ScrollPanel: TypeError: Cannot read properties of null (reading 'scrollWidth')

Fix #4689 - ScrollPanel: TypeError: Cannot read properties of null (reading 'scrollWidth')

---

pages/playground/index.vue

This PR just fixes a typo in the playground page, from 'interative' to 'interactive'

fix: typo in playground

---

components/lib/overlaypanel/OverlayPanel.vue

Fix [#4712 ](https://github.com/primefaces/primevue/issues/4712) Overlaypanel: Overlaypanel closes when any key is pressed. It should be closed when the "Escape" key is pressed.

Fix #4712 Overlaypanel: Overlaypanel closes when any key is pressed

---

components/lib/calendar/Calendar.vue

Fix #4732 - Calendar: Console.Error/Crash when pressing Escape key using Inline Calendar

Fix #4732 - Calendar: Console.Error/Crash when pressing Escape key using Inline Calendar

---

modules/nuxt-primevue/runtime/plugin.client.js

This is a DX improvement when developing - we can avoid loading the entire barrel file at `#app` by using the new granular imports merged in https://github.com/nuxt/nuxt/pull/23951.

fix: import nuxt composables from #imports

---

components/lib/passthrough/tailwind/index.js

The issue has been addressed by adding the "z-10" Tailwind class to the toolbar class in order to position it over the image.
Issue : [#4650](https://github.com/primefaces/primevue/issues/4650)

Fix #4650 -  Adding the "z-10" Tailwind class to the toolbar class

---

components/lib/passthrough/tailwind/index.js

The issue of max height not working was resolved by changing the class from "max-h-90" to "max-h-[90%]" with arbitrary percentage values.
Issue : [#4653](https://github.com/primefaces/primevue/issues/4653)

Fix #4653 - Edit dialog tailwind class

---

components/lib/inputnumber/style/InputNumberStyle.js

Fixes [#4516 ](https://github.com/primefaces/primevue/issues/4516)

Fix "InputNumber: float label initially broken if allowEmpty = false"

---

doc/inputgroup/CheckboxDoc.vue

Changed the wrong Endtags in the Check & Radio Example for InputGroup

Fix #4846: Change Endtags for Composition API example

---

src/components/orderlist/OrderList.vue

This PR fixes a bug in the OrderList component when moving multiple items to the top or bottom.
Fixes #4700
When multiple items are selected and moved to the top or bottom of an OrderList at the same time, they are moved one by one in a loop until the entire selection has been moved.
To make sure that the item at the top of the selection (the selected item that is highest up in the current order) will still be at the top after the selection, we should move items in the right order: move the top item last when inserting at the top, and first when inserting at the bottom. Currently, this order is exactly reversed, meaning the selected items are reversed in those cases. 
This commit reverses both loop orders to fix this problem

OrderList: keep correct order when moving multiple to top or bottom

---

src/components/calendar/Calendar.vue

Fix #4586 Crashes when Tab pressed and calendar overlay is not showing

---

components/lib/calendar/Calendar.d.ts
components/lib/calendar/Calendar.vue

Closes #4669
This PR adds slots around the week column header and individual week cells to allow for greater customization.

feat(calendar): Calendar week number slots

---

components/lib/calendar/Calendar.vue

Potential fix for #4901.
Includes date when formatting and parsing in time-only mode, preventing override of initial date value to `new Date()`.

#4901 - parse date when in time-only mode

---

components/lib/tree/Tree.d.ts
components/lib/tree/Tree.spec.js
components/lib/tree/Tree.vue

Fix #4876
To control the `expandedKeys` after the user updates their filter-input, it is needed to notify the parent component of this update.
This PR suggests adopting the same `filter` event that is present on similar components.
I also fixed a jsdoc missmatch in `Tree.d.ts:442`

Add 'filter'-event to Tree.vue

---

components/lib/image/style/ImageStyle.js

#4986: Image: Toolbar is hidden when the image is zoomed

Fix #4986: Toolbar is hidden when the image is zoomed

---

components/lib/basecomponent/style/BaseComponentStyle.js
components/lib/calendar/Calendar.vue
components/lib/cascadeselect/style/CascadeSelectStyle.js
components/lib/confirmdialog/ConfirmDialog.d.ts
components/lib/datatable/DataTable.vue
components/lib/datatable/style/DataTableStyle.js
components/lib/dialog/Dialog.d.ts
components/lib/dialog/Dialog.vue
components/lib/dialog/style/DialogStyle.js
components/lib/message/style/MessageStyle.js
components/lib/overlaypanel/OverlayPanel.d.ts
components/lib/overlaypanel/OverlayPanel.vue
components/lib/paginator/Paginator.vue
components/lib/picklist/style/PickListStyle.js
components/lib/ripple/style/RippleStyle.js
components/lib/sidebar/style/SidebarStyle.js
components/lib/toast/Toast.vue
components/lib/treetable/style/TreeTableStyle.js
doc/timeline/TemplateDoc.vue

Fix #4637 - Component Styles: Remove use of !important now that @layer is used
Copy of: https://github.com/primefaces/primereact/pull/5097

Fix #4637 - Component Styles: Remove use of !important now that @layer is used

---

components/lib/dropdown/Dropdown.vue

Fix #4567 - DropDown: Labels unassociated from DropDown unless :editable="true"

Fix #4567 - DropDown: Labels unassociated from DropDown unless :editable="true"

---

pages/bulma/index.vue

This PR fixes the misspelling of the word "components" in the docs, as can be seen [here](https://primevue.org/bulma/).

Fix typo in bulma documentation

---

api-generator/components/dropdown.js
components/lib/dropdown/BaseDropdown.vue
components/lib/dropdown/Dropdown.d.ts
components/lib/dropdown/Dropdown.vue
doc/common/apidoc/index.json
doc/dropdown/FilterDoc.vue

fix: Primefaces#5060, Dropdown: After selecting an option, clearing the value using close icon should clear the filter input

fix: Primefaces#5060, Dropdown: After selecting an option, clearing the value using close icon should clear the filter input

---

components/lib/splitter/Splitter.vue

Similar to a fix just made in PrimeReact: https://github.com/primefaces/primereact/pull/5884/files
The keyboard was using `setTimeout` instead of `setInterval`

Splitter: Fix keyboard repeat behavior

---

components/lib/inputswitch/InputSwitch.d.ts

This [commit](https://github.com/primefaces/primevue/commit/99b1edd5cedddbd12d72b24fcd240abe18b308b5) removed the `inputProps` property from the `InputSwitch` and some more components. The documentation currently still shows that this is a valid prop for the `InputSwitch` component https://primevue.org/inputswitch/

Remove missed inputProps from InputSwitch

---

components/lib/config/PrimeVue.d.ts

Fixes typing on the PrimeVuePTOptions.global.css property. Previously it would not accept just a string (had to be a function).

Fix PrimeVuePTOptions.global.css (missing parenthesis)

---

components/lib/autocomplete/AutoComplete.d.ts
components/lib/badge/Badge.d.ts
components/lib/button/Button.d.ts
components/lib/calendar/Calendar.d.ts
components/lib/cascadeselect/CascadeSelect.d.ts
components/lib/colorpicker/ColorPicker.d.ts
components/lib/contextmenu/ContextMenu.d.ts
components/lib/datatable/DataTable.d.ts
components/lib/dialog/Dialog.d.ts
components/lib/dropdown/Dropdown.d.ts
components/lib/inlinemessage/InlineMessage.d.ts
components/lib/listbox/Listbox.d.ts
components/lib/menu/Menu.d.ts
components/lib/message/Message.d.ts
components/lib/multiselect/MultiSelect.d.ts
components/lib/overlaypanel/OverlayPanel.d.ts
components/lib/password/Password.d.ts
components/lib/portal/Portal.d.ts
components/lib/splitbutton/SplitButton.d.ts
components/lib/styleclass/StyleClass.d.ts
components/lib/tag/Tag.d.ts
components/lib/tieredmenu/TieredMenu.d.ts
components/lib/tree/Tree.d.ts
components/lib/treeselect/TreeSelect.d.ts
components/lib/treetable/TreeTable.d.ts
components/lib/ts-helpers.d.ts

Fixes https://github.com/primefaces/primevue/issues/5285
Before:
After:

Fix #5285 - Improve string type hints DX

---

components/lib/inputotp/InputOtp.vue

fixed #5394 | replace isIntegerOnly with integerOnly

---

components/lib/datatable/BaseDataTable.vue

This pull request addresses an issue with the `DataTable` component's `rowClass` property type definition. Previously, the type was incorrectly defined as `[String, Object]`, which does not accurately reflect the intended usage and functionality. This fix updates the type definition to `[Function]`, aligning with the component's capability to accept a function for dynamically assigning classes to rows based on their data.
- [#5341](https://github.com/primefaces/primevue/issues/5341)
- [#5349](https://github.com/primefaces/primevue/issues/5349)
These issues highlight the confusion and type errors encountered by developers due to the incorrect type definition. This PR aims to resolve these concerns by correcting the `rowClass` type.
The `rowClass` property's type definition has been updated …

Fix `rowClass` Type Definition in `DataTable`

---

components/lib/inputnumber/InputNumber.vue

Fix #5008 
@tugcekucukoglu this cleans up the InputNumber keydown to match PrimeReact.
1. Removed `console.log`
2. Moved all short circuits to the top of the method that `return`
3. Removed unreachable check for `altKey`

Fix #5008  InputNumber: Cleanup KeyDown

---

components/lib/tree/Tree.d.ts
components/lib/tree/Tree.spec.js
components/lib/tree/TreeNode.vue

See #5452 
Pass the given classes down to the slot, so they can be used as usual.

(fix)Tree: Pass class to TreeNodes nodeIcon slot

---

components/lib/calendar/Calendar.vue

resolves https://github.com/primefaces/primevue/issues/5294
(I have tested this change with reproduction in the attached issue and can confirm that applying a fixed width is the exact reason why the enter transition is broken.)

fix(Calendar): when inline, do not apply fixed width to overlay

---

components/lib/calendar/Calendar.d.ts

As the calendar only allows to select two values, which one of them can be null (first range item selected, second not) the types should be precise and declared as tuple, and not allow arrays of unspecified length.
Fixes #3609

Fixes #3609 - Update Calendar typings to be precise

---

api-generator/components/carousel.js
components/lib/carousel/Carousel.vue

Small feature request as posted in the following
[Discussion: 1455](https://github.com/orgs/primefaces/discussions/1455)
Added an Empty slot so that the component behaves similar to other data components. e,g, DataView, DataTable

Carousel - Empty Slot

---

doc/theming/styled/DarkModeToggleDoc.vue

The darkModeSelector requires a leading dot for class selectors.

fix(Doc): Update DarkModeToggleDoc.vue - class selector needs dot

---

components/lib/carousel/Carousel.vue

Fix https://github.com/primefaces/primevue/issues/5320 (and address the actual issue with https://github.com/primefaces/primevue/issues/1837) blocking touch scrolling  by only cancelling the touchmove event if we detect a swipe that would change the carousel rather than blocking all touchmove events.

Fix #5320 – Carousel blocking touch scroll

---

components/lib/inputnumber/InputNumber.vue

Fix #5508: InputNumber allow AZERTY keyboards
Same fix was already implemented and confirmed in PrimeReact

Fix #5508: InputNumber allow AZERTY keyboards

---

components/lib/inputnumber/InputNumber.vue

event.key could be be used instead of event.code, because event.code doesn't take keyboard layout into account.
This should fix #5577.
"The KeyboardEvent.code property represents a physical key on the keyboard (as opposed to the character generated by pressing the key). In other words, this property returns a value that isn't altered by keyboard layout or the state of the modifier keys."
source: [https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code)
"The [KeyboardEvent](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent) interface's key read-only property returns the value of the key pressed by the user, taking into consideration the state of modifier keys such as Shift as well as the keyboard …

fix(#5577): Use event.key instead of event.code for determining digits

---

components/lib/tree/TreeNode.vue

Previously the options were not passed, so the classes were missing in unstyled mode
fixes #5574

fix: pass passthrough options to the nodeicon slot

---

api-generator/components/knob.js
components/lib/knob/BaseKnob.vue
components/lib/knob/Knob.d.ts
components/lib/knob/Knob.spec.js
components/lib/knob/Knob.vue
doc/common/apidoc/index.json
doc/knob/TemplateDoc.vue

Though #1027 is closed, I had a use case for more flexible labeling and decided to see if I could make this happen. My use case is that I am using the `Knob` component to show progress toward a goal; the data is kept in minutes, but the display should format it to show hours and minutes. There's no way to do that with a template string, so I hope that this PR gets accepted soon.
To be honest, this PR isn't doing much that isn't already implemented in https://github.com/kramer99/vue-knob-control/blob/master/src/KnobControl.vue. I retained the ability to pass a template string for backward compatibility. I also specifically checked to make sure that reactivity still works when a function was passed, since that was the original reason to reject #1027.
I also added tests for both a string …

Fixed #1027 - Knob: Allow a label function for greater flexibility

---

doc/nuxt/configuration/ComponentsDoc.vue

In the documentation for configuring the Nuxt module components, there is no indication that `Chart` and `Editor` are excluded by default. The only way to find out is if you happen upon a single issue in the github repo of the nuxt module npm package or read the full source code of the module. Although the intention of this default behavior is to avoid compatibility issues because of the dependencies of those 2 components, it leads to even more confusion when you know what they need but they aren't being detected as components. They are excluded even if you use the `'*'` option in `include`. This change introduces a helpful tip into the docs page so users know what to do when they want to use those components. The solution is to set `exclude` to `[]`.
issue #5583

Explain the default exclude option in the Nuxt module configuration docs.

---

components/lib/scrollpanel/ScrollPanel.vue

Fixes #5518 by making the check for setting the `this.$refs.xBar` and `this.$refs.yBar` attributes more defensive.

fix #5518: prevent erros thrown by ScrollPanel loading

---

components/lib/treetable/TreeTable.vue

Simple tweak fixing `filterField` usage in `TreeTable`

Fix TreeTable not using filterField

---

components/lib/sidebar/BaseSidebar.vue
components/lib/sidebar/Sidebar.spec.js

After a `Sidebar` component is already mounted, changing the `dismissable` prop has no effect. The initial value is the one that affects until hiding and re-showing the sidebar.
Even after the sidebar is shown, changing the value of `dismissable` prop should change the dismissability of the component.
Close: #5563

fix(sidebar): dismissable property should still be reactive after mount

---

components/lib/calendar/Calendar.vue

When the "Today" button is clicked, the hours field is set to 00 instead of the current hour. The minutes field is populated correctly.

Fixed #5596 - Calendar: Hours are set to 00 when clicking the "Today" button

---

api-generator/components/fileupload.js

This prop is a boolean, not a string, so I was unable to see why the locale was relevant. Seems like a copy/paste artifact.

[FileUpload] Remove incorrect sentence in customUpload prop docs

---

components/lib/datatable/DataTable.d.ts

This fixes an incorrect type definition in issue #5498 and improves the usage documentation for rowClass and rowStyle

fix(DataTable): fix rowClass type definition and improve usage documentation for rowClass and rowStyle. Fixes #5498

---

doc/button/LoadingDoc.vue

Fixed incorrect icon name from 'check' to 'search'.

docs(LoadingDoc.vue): Fixed incorrect icon name from 'check' to 'search'.

---

components/lib/inputnumber/InputNumber.vue

fix: disable paste functionality in readonly mode

---

components/lib/inputotp/InputOtp.vue

fix: primevue #5740, InputOtp: Able to paste otp in readonly and disabled modes

fix: primevue #5740, InputOtp: Able to paste otp in readonly and disabled modes

---

components/lib/popover/Popover.vue

This fixes the problem of using an incorrect design token namen for arrow positioning, described in #5755

Popover: use correct design token for arrow positioning, fixes #5755

---

doc/tabs/TabMenuDoc.vue

The docs sample code TabMenu in Tabs is currently missing the Tabs component around with. TabList requires to be embedded in a Tabs component. Without the component there will be $pcTabs errors. 
This patch adds the Tabs component to the sample code. The stackblitz has to be updated as well.

doc(Tabs/TabMenu): add missing Tabs component to sample code

---

assets/menu/menu.json

There are 3 meanings to the word "Sass":
* **The Syntax** - "Sass" or "Indented syntax" is a white-space dependent implementation of the language without curly braces or semi-colons. Since the other syntax, "SCSS", stands for "Sassy Cascading Style Sheets", a *bacronym* was created for "Syntactically Awesome Style Sheets". Despite having an acronym, "Sass" has officially *never* been put in all caps.
* **The Language** - "Sass" is generally used to refer to both syntax options, as they are 100% interchangeable, supporting identical features, in slightly different syntax.
* **The Processor** - A tool to process `.sass` and `.scss` files to valid `.css`. Technically there are many processors that exist to do this task, but when speaking genrally about them, they are often referred to as …

Sass, not SASS

---

components/lib/datatable/DataTable.vue

- fixed #5757
- I have modified the code to meet the following conditions :)
- `control + c` is working
- when multiple select mode, `control + a` is working and outer content of table is not select.
- when single select mode, `control + a` is not working and outer content of table is not select.
https://github.com/primefaces/primevue/assets/37934668/91732b7e-4472-4acc-8f48-ceb23a5a2bbe

fix(DataTable): allow control c key for copy a table content. (#5757)

---

components/lib/treenode/TreeNode.d.ts

This property is documented as mandatory.
Suggesting to remove `?` so that in my own code I no longer have to add not-null assertions like `.node.key!`.

types: Make TreeNode.key required

---

components/lib/dropdown/Dropdown.vue

- fixed #4488 
<br/>
- Horizontal scrolling occurs at the top-level element.
- There is a dropdown inside a dialog modal.
- When opening the modal and trying to select from the dropdown, the horizontal scroll shifts.
<br/>
- If you want to reproduce the issue, you can add the following code in the master branch and test it.
> assets/styles/layout/_core.scss
```scss
// overflow-x: hidden;
```
> pages/sample/index.vue
```vue
<template>
<div>
<div :style="{ backgroundColor: 'red', width: '200vw', height: '20px' }"></div>
<Dialog v-model:visible="visible" modal header="My modal" :style="{ width: '50vw' }">
<Dropdown v-model="selected" :options="items" placeholder="Select an item" />
</Dialog>
<Button label="Open Modal" @click="visible = true" />
</div>
</template>
<script>
import Dropdown …
```

fix(Dropdown): prevent horizontal scroll, when dropdown item selecting

---

components/lib/dropdown/Dropdown.d.ts
components/lib/listbox/Listbox.d.ts
components/lib/multiselect/MultiSelect.d.ts
components/lib/treeselect/TreeSelect.d.ts
doc/common/apidoc/index.json

Fixed the documented default value for the "emptyMessage" property for the Dropdown, Listbox, MultiSelect and TreeSelect components. They were all incorrectly documented as having a default value of "No results found". I changed each one to "No available options".

Fix documented default for emptyMessage on several components

---

components/lib/datatable/DataTable.d.ts

Fixes #5862
Change DataTableSortMeta `field` type to match DataTableSortEvent `sortField` type.

fix(types): DataTable: add function support to DataTableSortMeta field

---

packages/primevue/src/checkbox/style/CheckboxStyle.js

The checkbox box currently uses the width design token for the height property. This fix changes it to the height token.

fix(Checkbox): use correct design token for checkbox height

---

README.md

@mertsincan
The package version not showing.
The URL of the icon has been changed

refactor: update Badge URL of packages version in README.md

---

packages/primevue/src/checkbox/Checkbox.d.ts
packages/primevue/src/checkbox/Checkbox.vue

This PR adds the indeterminate state to the icon slot so it will be possible to customize the indeterminate icon as well as customize the unchecked icon when using indeterminate. 
Fixes #5942

feat(Checkbox): add indeterminate state to icon slot, fixes #5942

---

apps/showcase/doc/theming/styled/DarkModeToggleDoc.vue

This fixes the documentation about toggling color scheme according to #5963.
The fix has been provided by @blevinelrp.

doc: Fix toggleColorScheme function in theming

---

packages/primevue/src/tablist/TabList.vue

fix: avoid `v-ripple` missing warn when Ripple is not been registered

---

packages/primevue/src/iconfield/style/IconFieldStyle.js

Fixes #6034 
This changes the css selector to select all inputs, except the leading/trailing ones. While this does allow icons to be placed at both sides of an input, it might not work properly when there are other decorations or html elements inside of the `IconField`.

Fix IconField when icons should appear at beginning and end.

---

packages/primevue/src/datatable/style/DataTableStyle.js

[#6036](https://github.com/primefaces/primevue/issues/6036l)
https://github.com/primefaces/primevue/assets/15907064/addf79d8-ab13-4a6e-91d9-2a338d15c5c3
https://github.com/primefaces/primevue/assets/15907064/de08f40b-4fd4-44cc-83e6-262cdea9cb4a
This modification fixes the bug where the table header overlaps due to the lack of background color when fixed columns are used. It is achieved by modifying CSS.

Fix: DataTable Frozen Columns the headers of fixed columns will overlap.

---

packages/primevue/src/select/Select.vue

fix: #6084, SELECT: hide clear button when options is empty in Dropdown

fix: #6084, SELECT: hide clear button when options is empty in Dropdown

---

packages/primevue/src/confirmdialog/ConfirmDialog.spec.js
packages/primevue/src/confirmdialog/ConfirmDialog.vue
packages/primevue/src/confirmpopup/ConfirmPopup.spec.js
packages/primevue/src/confirmpopup/ConfirmPopup.vue

fix: missing default labels in ConfirmDialog and ConfirmPopup

---

packages/primevue/src/colorpicker/BaseColorPicker.vue

Fix: Add inputId Prop to BaseColorPicker Component 

---

packages/core/src/config/PrimeVue.js

Fixes #6125 (and possible other locale and custom options via .use related issues)
Custom options were being _shallow_ merged with default options (instead of **deep merge)**, overriding all nested properties. This PR resolves this utilizing _mergeKeys_ from `primeuix/utils`.

#6125 Fix (DatePicker, Locale) - deep merge options during install

---

packages/primevue/src/datepicker/DatePicker.vue

- fix #6081
- I modified the isValid value to allow the start date and end date to be the same.
```js
if (this.isRangeSelection()) {
isValid = value.length > 1 && value[1] > value[0] ? true : false; // before
}
```
```js
if (this.isRangeSelection()) {
isValid = value.length > 1 && value[1] >= value[0]; // after
}
```
https://github.com/user-attachments/assets/e8ae6d4c-7ba2-4dc0-95f4-e9bae955b1e1

Fix(DatePicker): allow to type the end date equal to the start date

---

components/lib/tree/TreeNode.vue

If node selectable is false then clicking the node shouldn't add the node to selectedKeys.
added selectable != false because selectable can be null | undefined | true to show the checkbox.
Fix for #5330

fix: TreeNode selectable not being used when in checkbox selectionMode

---

packages/primevue/src/confirmpopup/ConfirmPopup.vue
packages/primevue/src/confirmpopup/style/ConfirmPopupStyle.js
packages/primevue/src/popover/style/PopoverStyle.js

This fixes https://github.com/primefaces/primevue/issues/5915
A few things:
- `ConfirmPopup` was defining `overlay.arrow.left` but there were no references to `overlay` design token
- `Popover` defines `popover.arrow.left`, but only uses `popover.arrow.offset`
- I renamed `overlay.arrow.left` to `confirmpopup.arrow.left` to follow convention (there is an existing `confirmpopup.arrow.offset`)
- I added `arrow.left` in the arrow CSS, as I believe the separate token `arrow.offset` was meant for a fixed offset based on arrow size
Result:
- Calculated `arrow.left` values for `confirmpopup` and `popover` are actually used in the positioning of the arrow to make it dynamic based on screen location. `arrow.offset` token is still used for arrow theming.

Fix positioning of overlay arrows

---

packages/primevue/src/confirmpopup/ConfirmPopup.vue
packages/primevue/src/dialog/Dialog.vue

Fixes #6139.
Cherry picked 2 commits:
* https://github.com/primefaces/primevue/commit/c7f9b9704f931d8a30daffe27ca22cab3409b8be fix : Dialog/Confirm re-focus original element on close
* https://github.com/primefaces/primevue/commit/760c98f9981683caee4b40adba321d4f385d223a Refactor https://github.com/primefaces/primevue/issues/5577

Dialog: Cherry pick 're-focus original element on close' fix to v4

---

packages/primevue/src/steppanel/StepPanel.d.ts

This removes the need to add a wrapper function that changes the type of activateCallback to any before calling it.
Fixes issue in #6225.

fix(Stepper): include panel value in activateCallback signature

---

apps/showcase/doc/popover/BasicDoc.vue

The Button in the code section of the popover documentation page did not have the same icon and label as the demo section.

Fixed Button in the popover basic doc to be consistent in both the demo and the code section

---

packages/primevue/src/datepicker/DatePicker.spec.js
packages/primevue/src/datepicker/DatePicker.vue

Fixes #6203. Added test for the issue.

#6203 fix: switching to year view when modelValue is populated

---

packages/primevue/src/datepicker/DatePicker.vue

- the `value` is undeclared, so i change `value` to `modelValue` ([related PR](https://github.com/primefaces/primevue/pull/5884/files?diff=split))

fix(DatePicker): change value to modelvalue in isYearSelected

---

packages/primevue/src/accordioncontent/AccordionContent.d.ts
packages/primevue/src/accordioncontent/BaseAccordionContent.vue
packages/primevue/src/accordionheader/AccordionHeader.d.ts
packages/primevue/src/accordionheader/BaseAccordionHeader.vue
packages/primevue/src/accordionpanel/AccordionPanel.d.ts
packages/primevue/src/accordionpanel/BaseAccordionPanel.vue
packages/primevue/src/button/BaseButton.vue
packages/primevue/src/button/Button.d.ts
packages/primevue/src/step/BaseStep.vue
packages/primevue/src/step/Step.d.ts
packages/primevue/src/steppanel/BaseStepPanel.vue
packages/primevue/src/steppanel/StepPanel.d.ts
packages/primevue/src/tab/BaseTab.vue
packages/primevue/src/tab/Tab.d.ts
packages/primevue/src/tabpanel/BaseTabPanel.vue
packages/primevue/src/tabpanel/TabPanel.d.ts

Fix invalid prop warnings when component object passed to `as` props in `AccordionContent`, `AccordionHeader`, `AccordiongPanel`, `Button`, `Step`, `StepPanel`, `Tab`, `TabPanel` components. [#6266](https://github.com/primefaces/primevue/issues/6266)
Commits were for each set of components and can be happily separated out to separate, individual PRs if necessary.

fix: extend as props to accept component objects

---

packages/primevue/src/menubar/MenubarSub.vue

- move getAriaSetSize to computed
- optimize getAriaPosInset
Fixes #6164
`getAriaSetSize` was a method iterating over the whole (or subset) of items. Moved this to computed as it doesn't need any args
`getAriaPosInset` - slightly optimized so it works with computed list instead of executing the filtering over whole list every time.

- fix #6164 optimize menu bar

---

packages/nuxt-module/package.json
pnpm-lock.yaml

Previous versions of `@nuxt/module-builder` produced incorrect types for files in the `runtime/` directory. Specifically, a `.d.ts` declaration paired with a `.mjs` file. This isn't correct - it should be either `.d.mts`  and `.mjs` or `.d.ts` and `.js`. 
For maximum compatibility, `@nuxt/module-builder` v0.8 switched to `.js` extension for files in `runtime/` directory.
With the latest Nuxt, this is now an error that removes correct plugin injection types.
Related PRs: https://github.com/nuxt/nuxt/pull/28480, https://github.com/nuxt/nuxt/pull/28593
See also https://github.com/nuxt/nuxt/issues/28672.

chore: update to latest `@nuxt/module-builder`

---

packages/primevue/scripts/components/dialog.js
packages/primevue/src/dialog/Dialog.d.ts
packages/primevue/src/dialog/Dialog.vue

This PR fixes #6356 - Dialog dragging state not reset when a dialog is closed while being dragged. \
It additionally resolves #6357 by adding a `dragstart` event to accompany the `dragend` event.

Dialog: fix #6356 and implement #6357

---

packages/primevue/src/inputotp/InputOtp.vue

fixes #6353 - InputOtp: IntegerOnly mode accepts "space"

fixes #6353 - InputOtp: IntegerOnly mode accepts "space"

---

packages/primevue/src/datatable/DataTable.spec.js
packages/primevue/src/datatable/DataTable.vue

Fixes: #6323 
- First, paste code to `<template>` of `CellEditDoc.vue`
- and you click cell, you can see the issue
```html
<div class="card">
<DataTable
:value="products"
editMode="cell"
selectionMode="single"
@cell-edit-complete="onCellEditComplete"
:pt="{
table: { style: 'min-width: 50rem' },
column: {
bodycell: ({ state }) => ({
class: [{ 'pt-0 pb-0': state['d_editing'] }]
})
}
}"
>
<Column v-for="col of columns" :key="col.field" :field="col.field" :header="col.header" style="width: 25%">
<template #body="{ data, field }">
<div>
{{ field === 'price' ? formatCurrency(data[field]) : data[field] }}
</div>
</template>
<template #editor="{ data, field }">
<div>{{ data[field] }} 1</div>
</template>
</Column>
</DataTable>
</div>
```
<br/>
- If you look at the video at the bottom, you can see …

fix: handle click event using event.currentTarget in DataTable

---

apps/showcase/doc/theming/styled/utils/PaletteDoc.vue

`palette()` returns key-value pairs, not an array.
Do one-word typo fixes like this need tickets?

Fix incorrect statement in palette() docs

---

packages/primevue/src/datatable/TableBody.vue

Fixes #6006
Fix missing `pt`/`unstyled` props on empty message table row

Fix DataTable: emptyMessage passthrough

---

packages/primevue/src/popover/Popover.d.ts

closes #6448 
The reference to the popover alias is no longer necessary and should be removed.

fix: remove needless description of popover

---

packages/primevue/src/speeddial/SpeedDial.vue

This PR adds a slot wrapped around the icon in the speed dial sub items.

Add itemicon slot similar to the one in the breadcrumbs component

---

packages/primevue/src/tree/TreeNode.vue

Nodetoggleicon slot is used to customize expand / collapse and loading icon, but when loading mode is set to icon mode and a node is loading, TreeNode use nodetoggleicon without any props instead of binding node and expanded.
This commit bind node and expanded props to nodetoggleicon slot when loading mode is set to icon and node.loading is true.

Fix #6371: Add node and expanded data on nodetoggleicon.

---

packages/primevue/scripts/components/tree.js
packages/primevue/src/tree/BaseTree.vue
packages/primevue/src/tree/Tree.d.ts
packages/primevue/src/tree/Tree.vue

See [discussion](https://github.com/orgs/primefaces/discussions/2659) for the idea.
This 1-line patch allows the `filterBy` prop of `<Tree>` to take a getter.
I'm using this successfully in my app, but this patch to primevue would allow me to unwind some workarounds.
Thanks for your consideration, keep up the great work!
Closes #6374

#6374 Tree: allow `filterBy` to be a getter

---

packages/primevue/src/datatable/BaseDataTable.vue
packages/primevue/src/datatable/DataTable.d.ts
packages/primevue/src/datatable/DataTable.vue

This PR adds property showHeaders to DataTable
Fixes #5949

Feat(DataTable): added showHeaders prop to datatable

---

packages/primevue/src/splitter/Splitter.d.ts
packages/primevue/src/splitter/Splitter.vue

Hello,
I'm encountering the issue #5463, and I don't think the approach proposed by matansha is ideal. Recalculating the "initial" state on every component update will reset user resize actions each time the component is updated, making it unusable.
One potential solution could be for the Splitter to observe changes on the size property of each SplitterPanel. However, this seems risky because these values might be updated simultaneously across all panels, leading to unintended frequent updates.
A more straightforward approach could be to introduce a reset function on the Splitter component, allowing users to manually re-run the initialization code (initializeState).
For those who want permanent synchronization, they could add a watcher on the size props to trigger a reset on each update. …

Proposal for #5463: Add a resetState method to splitter to manually reset state

---

packages/primevue/src/datatable/DataTable.vue

Fixes #6014 by removing the double counting of the page scroll position.
The `getOffset()` utility function already includes the window's scroll position (see [here](https://github.com/primefaces/primeuix/blob/20388c576629d62cc9625ba87c1975aba78f85ef/packages/utils/src/dom/methods/getOffset.ts#L6-L7)). Double counting the scroll offset meant that the DataTable `onRowDragOver` event handler always thought we were on the top-half of the row, preventing the indicator from being shown at the bottom of the row.

fix DataTable: Allow drop below bottom row

---

apps/showcase/doc/fileupload/TemplateDoc.vue

Update regarding [#6404](https://github.com/primefaces/primevue/issues/6404) to add `messages` to `content` template of `FileUpload` example. 
If any one in the team thinks this extension makes sense, the StackBlitz live example would also require updating for full effect.

#6404 fix: add messages to FileUpload templates

---

packages/primevue/src/inputmask/InputMask.vue

- fix #6276
<br/>
- In version 3 ([v3](https://github.com/primefaces/primevue/blob/v3/components/lib/inputmask/InputMask.vue#L2C5-L2C60)), there was no issue of value mixing when in unmask mode. 
- This is because v3 used native input rather than `inputText component` and did not pass the value dynamically.
- However, in version 4 (v4), `inputText component` is used, which dynamically receives the value. 
- This causes an issue where the unmasked value is sent with `update:model-value`, leading to value updates being corrupted.
<br/>
> based on the behavior of v3, the following modifications were made:
1. `currentVal` variable was declared to display the masked value in inputText, regardless of whether it is in unmask mode.
2. The unmasked value is sent with `update:model-value` when …

fix: emit unmask value to update:modelValue when unmask mode

---

packages/primevue/src/datatable/HeaderCheckbox.vue

fix: add unstyled prop to HeaderCheckbox component

---

components/lib/dialog/Dialog.vue

For fixing the issue in `primevue v3`: https://github.com/primefaces/primevue/issues/6162
When the dom is not fully `entered`, triggering the `focus` event will cause the browser force to settle the doms. So we may need to postpone the `focus` event.

fix: fix the unexpected joggle state when `dialog` component non-fixed

---

packages/primevue/src/password/BasePassword.vue
packages/primevue/src/password/Password.vue

- Fix: #6413.
- Modify `BasePassword.vue` to allow `<Password>` component can receive `autofocus` attribute.
```
<Password v-model="value" autofocus :feedback="false" />
```
- AS-IS
https://github.com/user-attachments/assets/3aa1d1d8-63dc-4424-a502-3b8b49024b32
- TO-BE
https://github.com/user-attachments/assets/dc12fe63-90cd-4e4e-9737-7810b505d19a

fix(Password): add 'autofocus' property on Password component

---

packages/primevue/src/select/Select.vue

- Fix: #6437
- It seems the original intent was to display "empty" when the label does not exist, but due to the behavior of the OR operator, the label is considered falsy when it is the number 0, causing "empty" to be displayed.
- Modify the code to use the Nullish Coalescing Operator instead, so that "empty" is only shown when the label is `undefined` or `null`.
- AS-IS
- TO-BE

fix(Select): replace logical OR Operator to Nullish Coalescing Operator

---

packages/primevue/src/select/Select.vue

closes #6420
closes #6420
Due to the setTimeout used in `hide` method, we need to execute focus 1ms after.

#6420 fix: Select: autoFilterFocus stuck when switching between Selects

---

packages/primevue/src/treeselect/BaseTreeSelect.vue
packages/primevue/src/treeselect/TreeSelect.vue

- fix: #5967
- `TreeSelect` can be considered an extended version of the Tree component.
- However, unlike the Tree component, it does not provide the `expandedKeys` functionality.
- This behavior seems to deviate from the intended design.
- Therefore, I modified it so that the `expandedKeys` function works similarly to the `Tree` component. :)
<details>
<summary>TreeSelect Test Sample Code</summary>
<template>
<div>
<Button @click="expandedKeys = { 0: true }">change expandedKeys value</Button>
<p>expandedKeys: {{ expandedKeys }}</p>
<hr />
<TreeSelect 
v-model="selectedValue" 
:options="nodes" 
selectionMode="checkbox" 
:expandedKeys="expandedKeys" 
display="chip" 
placeholder="Select Item" 
class="md:w-20rem w-full" 
:removeable="true" 
@update:expandedKeys="setExpandedKeys" 
/>
</div> …

feat: add expandedKeys, update emit event in TreeSelect

---

packages/primevue/scripts/components/splitter.js

fixes https://github.com/primefaces/primevue/issues/6570

 fix(Splitter): #6570 (Typo in splitter.js (autocomplete err))

---

apps/showcase/doc/tooltip/DelayDoc.vue

Fixes typo in popover docs page for "delay"

fixed typo in delay doc

---

packages/core/package.json

closes #6492
the `slots` argument of _DefineComponent, which is used in [here](https://github.com/primefaces/primevue/blob/master/packages/core/src/index.d.ts#L17), is introduced in vue 3.3 (see https://github.com/vuejs/core/commit/5a2f5d59cffa36a99e6f2feab6b3ba7958b7362f and https://github.com/vuejs/core/commit/bdf557f6f233c039fff8007b1b16aec00c4e68aa).
Therefore, I think we should bump vue version of peerdependency.

bump vue version

---

packages/primevue/src/slider/Slider.vue

This PR fixes [#5745](https://github.com/primefaces/primevue/issues/5745).
The event.preventDefault() method has been removed.
The touch event uses the .passive modifier, and also uses the preventDefault method. On mobile devices, the browser will report an error.
The official documentation for Vue.js is as follows:
https://vuejs.org/guide/essentials/event-handling.html#event-modifiers
Do not use .passive and .prevent together, because .passive already indicates to the browser that you do not intend to prevent the event's default behavior, and you will likely see a warning from the browser if you do so.
Due to company policy, we are unable to accept feature request PRs with …

fix: Slider: "Unable to preventDefault inside passive event listener invocation" in primevue_slider.js (touchmove)

---

packages/primevue/src/slider/Slider.spec.js
packages/primevue/src/slider/Slider.vue

**Defect Fixes**
Fixes #6649
**Cause**
The slider component didn't handle certain range values correctly when the min and max properties were set, particularly when the range included zero and the model value started at zero.
**Example:**
- Create a slider with min = -100 and max = 100.
- Set modelValue = [0, 50].
In this setup:
Values like [1, 50] and [-1, 50] render correctly within the range. However, when the range starts exactly at 0, the slider incorrectly renders to the left instead of between -1 and 1 as expected.
This issue occurred because the slider's position calculation didn't consider cases where the starting value of the range (0) was at the center of the [min, max] boundary.
**Solution**
I changed the rangeStartPosition and rangeEndPosition logic a little bit:
- …

fix(slider): correct range operation bug

---

packages/primevue/src/dynamicdialog/DynamicDialog.vue

Fix [Issue #6535](https://github.com/primefaces/primevue/issues/6535)
The dialog data was not being destroyed upon closing, leading to unnecessary memory consumption as the object was no longer used. The dialog component wasn't being destroyed even when it was no longer needed.
Destroy the instance data from the map when it is closed, ensuring that unused memory is released.

fix: Destroy dialog instance on close to release unused memory

---

packages/primevue/src/inputotp/InputOtp.vue

This resolves the jumbled input when using the autocomplete feature in iOS/macOS to fill a one-time-code field (#6317).
iOS/macOS sends a CustomEvent vs. an InputEvent, and thus has no `inputType`. However, it does still need to move to the next input field, otherwise the next character is just appended after the first, resulting in 123456 becoming 165432.
I have confirmed that the proof of concept handler used here works: https://stackblitz.com/edit/primevue-4-vite-issue-template-kmmtvs?file=src%2FApp.vue
However, I am unsure of whether there might be other CustomEvents that would fire that would not want to move to the next field. Unfortunately, there were no other identifying characteristics of the event that Apple sends that I could use in order to limit the impact of this change.

Fix #6317 InputOtp

---

packages/primevue/src/textarea/Textarea.vue

- fix #4510
<br/>
- When `v-show` is applied to a parent element, the height of the TextArea is not automatically adjusted.
- This happens because the TextArea component does not detect visibility changes.
- The `updated` hook in the TextArea is only triggered by changes in its reactive data or props, and it doesn't respond to the parent’s v-show changes.
- To address this, I implemented ResizeObserver.
- ResizeObserver detects size changes in elements and can also respond to visibility changes caused by the parent’s v-show.
- This ensures that the TextArea automatically adjusts its height when the parent’s visibility changes.
<details>
<summary>test sample code</summary>
```js
<template>
<span v-show="value.display === true">
<div>
<Textarea id="xxx" v-model="value.text" autoResize …
```

fix(TextArea): autoResize issue with v-show by implementing ResizeObserver

---

packages/primevue/src/treeselect/TreeSelect.vue

- fix: #4927
<br/>
- In "appendTo: self" mode, clicking the overlay expand icon causes the overlay to close unexpectedly.
- This happens because clicking the expand icon triggers the onClick event of the container ref.
- I have prevented event propagation when clicking the overlay in "appendTo: self" mode.
```js
<TSTree
@click.stop  // added
... 
/>
```
<details>
<summary>sample code</summary>
```js
<template>
<div class="card flex justify-center">
<TreeSelect v-model="selectedValue" :options="nodes" placeholder="Select Item" class="md:w-80 w-full" append-to="self" />
</div>
</template>
<script>
import { NodeService } from '/service/NodeService';
export default {
data() {
return {
nodes: null,
selectedValue: null
};
},
mounted() {
NodeService.getTreeNodes().then((data) => (this.nodes = …
```

fix(TreeSelect): prevent event propagation when clicking overlay

---

packages/themes/src/presets/material/toggleswitch/index.js

**Defect Fixes**
Fixes #6735 
**Cause**
The issue occurred because the design token `toggleswitch.gap` was set to 0 without a unit, which caused inconsistencies when used in a calc() function within the inset-inline-start property.
**Solution**
Updated `toggleswitch.gap` from 0 to 0px

fix(toggleswitch): ensure visual switch with Material theme

---

packages/primevue/src/togglebutton/ToggleButton.vue

fix: correct empty label rendering to display non-breaking space

---

packages/primevue/src/datepicker/DatePicker.vue

Fix: If we select 24hrs it is not matich input value and templete value.
Bug: (https://github.com/primefaces/primevue/issues/6824)

fix: update time format in 12 hrs format if hourFormat is 12hrs

---

packages/primevue/src/knob/Knob.d.ts

[Issue #6843](https://github.com/primefaces/primevue/issues/6843)
This pull request fixes the TypeScript definition for the `valueTemplate` prop in the `Knob` component. The previous type declaration:
```typescript
valueTemplate?: (val: number) => string | string | undefined;
```
was incorrect and caused the prop to only accept functions, as `string | undefined` was interpreted as the return type of the function. This made it impossible to directly assign a `string` value to the `valueTemplate` prop.
The updated type:
```typescript
valueTemplate?: ((val: number) => string | undefined) | string;
```
correctly allows the prop to accept either:
- A function that returns `string | undefined`.
- A plain `string` value.
- Or remain undefined.
This change ensures the …

Knob (Typescript): Fix valueTemplate prop type definition

---

packages/primevue/src/inputnumber/InputNumber.vue

Here is the [Issue link](https://github.com/primefaces/primevue/issues/6837) that was fixed on this PR. The creator of the issue provided clear description of the issue.

Fix #6837 - Updated onInputKeyDown() on InputNumber so that it works as expected

---

packages/primevue/src/carousel/Carousel.vue

- fix: #6812
<br/>
In autoplay mode, when the count of value is less than or equal to this.d_numVisible, a bug causing white space to appear occurs.
To resolve this, I validate that the count of value is sufficient.
```js
hasValidItemCount() {
return this.value && this.value.length > this.d_numVisible;
},
```
> Before: White space appeared.
https://github.com/user-attachments/assets/27cffe2e-b873-415b-8ee0-a992c6de48f4
<br/>
> After: Autoplay is disabled, and the item is displayed correctly.

fix(Carousel): allow autoplay when value has valid count

---

packages/primevue/src/datatable/DataTable.vue

- fix: #6904
> Before: When clicking on the empty space of the outer DataTable, the error occurred.
https://github.com/user-attachments/assets/913ff06b-00eb-4c8b-962e-b4bb94ccd381
> After: When clicking on the empty space of the outer DataTable, the error no longer occurs.
https://github.com/user-attachments/assets/320a6355-e394-4084-b598-98ae427ef16c

fix(DataTable): update tabIndex when targetRow exists

---

packages/forms/src/form/Form.d.ts

Resolve #6717
Fix $form type error when using form fields

Fix $form type error

---

packages/primevue/src/datepicker/DatePicker.vue

The fix for below bug, checking the `date-format` prop and and formatting the date based on the `date-format` value
Fix: https://github.com/primefaces/primevue/issues/6930

fix: format date intially

---

packages/primevue/src/treeselect/TreeSelect.vue

Fixes #6950
You can read a detailed explanation in the issue.
Here’s how I measured performance for the current version:
```
selectedNodes() {
let selectedNodes = [];
if (this.d_value && this.options) {
let keys = { ...this.d_value };
performance.mark('findSelectedNodesStart');
this.findSelectedNodes(null, keys, selectedNodes);
performance.mark('findSelectedNodesEnd');
const perfResult = performance.measure('findSelectedNodesDuration', 'findSelectedNodesStart', 'findSelectedNodesEnd');
console.log(`findSelectedNodes duration: ${perfResult.duration}`);
}
return selectedNodes;
}
```
And here’s how I measure it for my solution:
```
nodeMap() {
const nodeMap = {};
performance.mark('nodeMapStart');
this.options?.forEach(node => this.fillNodeMap(node, nodeMap))
performance.mark('nodeMapEnd'); …
```

fix: Performance issue for TreeSelect component

---

packages/primevue/src/dynamicdialog/DynamicDialog.vue

Defect Fixes #6956 
Before this fix, the dialog instance was removed immediately on hide, which could cause issues with the closing animation. Now the instance is properly removed after the animation completes in the after-hide event.

fix(DynamicDialog): delay instance removal until after hide animation

---

packages/primevue/src/datatable/BodyCell.vue

- fix: #6572
<br/>
> Commits: [[3763298](https://github.com/primefaces/primevue/pull/6984/commits/37632982a94b3ecbd0a656059cc5f58dc043fbe2), [b5ca685](https://github.com/primefaces/primevue/pull/6984/commits/b5ca6858a99e650c0f23ebb725046897924bf500)]
- When changing and reflecting a cell's value, the primary events involved are `cell-edit-init` and `cell-edit-complete`.
- The `cell-edit-init` event initializes the cell's default values based on the current rowData.
- When the `cell-edit-complete` event is triggered, it updates the cell with the modified value.
- However, if the DataTable sorts the data when the `cell-edit-complete` event occurs, it results in the previous data remaining in the cell. 
- This happens because when navigating from Cell A to Cell B, the event sequence is: …

fix(DataTable/BodyCell): apply updated cell value after value sorting

---

packages/primevue/src/splitbutton/SplitButton.d.ts

fix: rename isBlocked to isExpanded in SplitButtonState interface

---

packages/primevue/src/datepicker/DatePicker.vue

Adds back the missing unstyled property to the minute decrement button for the datepicker
Fixes issue #7004

Fix missing unstyled property inside decrement minute button

---

apps/showcase/doc/guides/primeflex/MigrationDoc.vue

Fixes a `pf2tw` command typo in the [PrimeFlex to Tailwind CSS Migration](https://primevue.org/guides/primeflex/#migration) Docs.

PrimeFlex to Tailwind CSS Docs Typo

---

packages/primevue/src/column/Column.d.ts

Set the type for the field `field` in the Column body slot to match the column field type

correct field type for column body slot

---

packages/core/src/baseeditableholder/BaseEditableHolder.vue

fix #6755
Added watcher in `BaseEditableHolder` component which listens for `$pcForm.state[inputName]` and changes `d_value` after reset action
I am not sure if it will be worth adding Event bus for this - discussion needed
Emit `reset` event from `Form` component and listen for that event in `BaseEditableHolder`.

Form: reset not working, changed value not update input

---

packages/core/src/base/style/BaseStyle.js

Fix #4214: Screenreader improve hidden accessible
Based on this PF ticket: https://github.com/primefaces/primefaces/issues/12577
Based on NVDA: https://github.com/nvaccess/nvda/issues/16300
This is the modern way to hide things but still make them screenreader visible.  Tested with JAWS and NVDA

Fix #4214: Screenreader improve hidden accessible

---

packages/primevue/src/drawer/Drawer.d.ts
packages/primevue/src/drawer/Drawer.vue

Enhancement: Add **_before-hide_** event to Drawer component.
Issue referance (https://github.com/primefaces/primevue/issues/6770)

Drawer: Add before-hide event to Drawer component

---

packages/primevue/src/toast/BaseToast.vue
packages/primevue/src/toast/Toast.d.ts
packages/primevue/src/toast/ToastMessage.vue

I understand you don't want feature PRs, however I did this before reading that so please consider this code change. This is not backwards breaking in any way and is simply a port of a feature that was added to PrimeReact two years ago. I used the [commit from that project](https://github.com/primefaces/primereact/commit/fd07f37c9d2052cdd947e9ed3424805c1eac50a4) as a guide to make this change and took great care to ensure the change was clean, concise and matches the existing code style.
The issue that PR was accepted for was https://github.com/primefaces/primereact/issues/3272
That being said, I didn't see any information in the README.md nor did I see a CONTRIBUTING.md file so I was not clear on how to set this up so I could test my code so be aware these changes have not been tested! …

Implements "pause on hover" Toast feature & exposes onMouseEnter and onMouseLeave callback props

---

packages/primevue/src/select/Select.vue

Fixes #6813 
Sets `aria-invalid` attribute on the `Select` label in non-editable mode as well

fix(Select): Set `aria-invalid` attribute in non-editable mode as well

---

packages/primevue/src/datepicker/DatePicker.vue

When using selectionMode = range, showTime and inline options together the component would not allow the time of the second date to be edited.
This seems like a bug to me rather than a intended behavior of the component.
If it is for some reason intended, it should be documented that this won't indeed work.

fix(date-picker): inline used together with range and time options

---

packages/primevue/src/tooltip/Tooltip.js

#7071 
Adding some edge detection when position is `top` or `bottom` and the tooltip is close to the left/right edge of the screen.
As a consequence of this when the tooltip is adjusted to fit inside the screen the tooltip arrow ends up being in the wrong position, fixed that as well.

#7071 enhance edge detection for tooltips

---

packages/primevue/src/button/Button.d.ts

Ideally the types would only suggest it when the asChild option is set to true, but I suspect that we cannot do that without composition API and the generic types - even then it could be very messy.

feat(button): add a11yAttrs to slot types

---

packages/primevue/src/menu/Menu.d.ts

The component does emit the show/hide events when it is being used as a popup, but the events were not documented.

docs(menu): add show/hide events to types and docs

---

packages/core/src/basecomponent/BaseComponent.vue
packages/core/src/basedirective/BaseDirective.js

Fixes #6715
- Implemented event callback cleanup on component unmounting
- Enhanced memory management through lifecycle hooks
- Maintained existing callbacks until full cleanup to preserve potential intentional behavior
1. Navigated through all component pages sequentially
2. Monitored memory usage patterns
3. Performed manual garbage collection after tests to ensure complete cleanup
- Reduced memory footprint:
Before: 
After:
Chose to implement cleanup on unmount as a conservative approach since the requirements weren't explicit about element persistence. I kept the existing callbacks until they are all removed, as I wasn't sure if their accumulation was intentional. This ensures cleaner memory management while maintaining component integrity.
---
I hope this helps resolve the bug. I'm …

Fix memory leaks

---

packages/primevue/src/button/Button.d.ts

The docs do show that the "to" prop is usable on the button, but the types don't support it, making it hard to use in typed components.
Ideally it would support all of the options that Vue Router accepts, but we would need the types from the Vue Router package which would have to be present on this project - out of my comfort zone with this repo for now, maybe a generic object type would atleast make it possible to use.
https://primevue.org/button/#link

feat(button): add to prop type

---

apps/showcase/doc/autocomplete/AccessibilityDoc.vue
packages/primevue/src/autocomplete/AutoComplete.vue

fix https://github.com/primefaces/primevue/issues/2930

feat(autocomplete): implement shift modifier interactions

---

apps/showcase/doc/editor/QuillDoc.vue
packages/primevue/src/editor/Editor.vue
packages/primevue/src/editor/style/EditorStyle.js

**Warning: Probably breaking change**
This PR changes the Editor component behavior for fetching the HTML content from using innerHTML to the new getSemanticHTML and updates list css to adjust to breaking changes in Quill 2.0. This will however cause the Editor component to no longer work with Quill < 2.

feat(Editor): improve quill 2 support by using getSemanticHTML and adjust list css for version 2, fixes #7061

---

packages/primevue/src/dialog/Dialog.vue

Fix https://github.com/primefaces/primevue/issues/6922
The closable prop is a little confusing as it's main purpose seems to be hiding of the button, but to me it sounds like it should prevent all closing. Ideally we would rename the prop and perhaps introduce a new one with more specific name, but that would be a breaking change.
Nevertheless this simple change should be enough to resolve the issue.

fix(dialog): escape closing when not closable via button

---

packages/primevue/src/dialog/Dialog.vue
packages/primevue/src/editor/Editor.vue

Fix https://github.com/primefaces/primevue/issues/6954
I could not find a reason why the color buttons needed to be rerendered. Perhaps an issue that was present in older versions of the editor? I checked the [original commit ](https://github.com/primefaces/primevue/commit/af50c82bb625c63227a72af5588bf9b8fb618e4d#diff-e626bf17f0814c503f89a012b676ff7f5c221683f8e49f51d8e4474e040a00ebR22)that introduced the `reRenderColorKey` property but there is no description about what it solves, maybe someone will take a look at this and know what's up.

fix(editor): broken color buttons after modelValue update

---

packages/primevue/src/splitter/Splitter.vue

Fix https://github.com/primefaces/primevue/issues/7001
The issue was due to premature validation - the user would move the mouse too fast skipping the values close to the minSize and we would evaluate that as invalid change (and it was), but we did not update the elements with the minimum size.
That is why when the minSize was set to 20 it could end up being anything above 20 even though the mouse was way beyond the min size limit.

fix(splitter): minSize behavior during fast mouse movement

---

packages/primevue/src/accordionheader/AccordionHeader.vue

Fix the direction of chevron icons for Accordion #7128

Fix reversed Expand/Collapse icons of AccordionHeader.vue

---

packages/primevue/src/floatlabel/style/FloatLabelStyle.js

Problem
When we modify the design token floatlabel.active.font.weight for [FloatLabel Theming](https://primevue.org/floatlabel/#theming.tokens), it is not applied correctly because the code uses the incorrect key floatlabel.label.active.font.weight.
Solution
Change the key used in the code to the correct floatlabel.active.font.weight

fix(floatlabel): correct font.weight style key weight for active label

---

packages/primevue/src/password/style/PasswordStyle.js

Add cursor pointer style to Password component's ToggleMask icon
- Added `cursor: pointer` style to the ToggleMask icon in Password component to improve user interaction feedback
When hovering over the ToggleMask icon, there was no visual indication that it was clickable. This small style enhancement improves the user experience by making it clear that the icon is interactive.

feat(Password): add cursor pointer to ToggleMask icon

---

packages/primevue/src/datatable/DataTable.vue

When selection mode is enabled, you cannot ctrl-c data in the table which is highly annoying, This was already fixed in Vue 3 using the following PR: https://github.com/primefaces/primevue/pull/5759
It's a very small patch that makes a huge difference.
https://github.com/primefaces/primevue/issues/6740

DataTable : Allow ctrl-c during selection mode (port from Vue 3 PR)

---

packages/primevue/src/fileupload/FileUpload.d.ts

Fix the wrong types of the `content` slot in the `fileupload` component.
Fix https://github.com/primefaces/primevue/issues/7189

fix(fileupload): fix the types of the `content` slot

---

packages/primevue/src/virtualscroller/VirtualScroller.vue

if you scroll to the bottom of the list you risk calling onScrollPositionChange many times.
I added an additional check
Reproducer: https://stackblitz.com/edit/rdjblce9-diu8ucun?file=src%2FApp.vue

fix(VirtualScroller): #7208

---

apps/showcase/doc/passthrough/DeclarativeDoc.vue

remove extra double quotes and replace class= with class:

fix(Passthrough): Typo - Fix declearativeDoc example typo

---

packages/primevue/src/datatable/DataTable.vue

The commit 01b38bf has introduced a recursive loop in the DataTable component trying to solve the #3818 issue.
Since the 3.45.0 version, we can't use rowGroupMode and v-model:filters together anymore (issues #5261, #5878). The browser tab freezes when we do it.
This PR fixes the following issues : #5261, #5878

fix: #5878, #5261 : DataTable recursive loop

---

packages/primevue/src/datatable/ColumnFilter.vue

_Note: It's not yet released, so I didn't create an issue._
In the current released version, the logic is just `filterIconTemplate || 'FilterIcon'`.
This was changed to `filterIconTemplate || hasFilter() ? 'FilterFillIcon' : 'FilterIcon'` in 6c0e96fdcc7c410bd5e3203932f61e298e71ff5b and 2bfc867ec0d1e7a62bee6725aea10219421b39c3.
Since the ternary operator has a higher precedence than the logical OR (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence#table), this logic now means "use `FilterFillIcon` if `filterIconTemplate` is truthy", which is wrong. This PR adds parentheses to fix this bug.

fix: restore filter icon override functionality

---

packages/primevue/src/autocomplete/AutoComplete.d.ts

Add missing properties removeCallback and index off chip scopedslot in Autocomplete.d.ts.
Fix #7235

Fix: Add removeCallback and index in Autocomplete chip slot definition

---

packages/primevue/src/tablist/TabList.vue

This PR fixed #7224 about wrong `inkBar` (indicator) position when putting default `value` to a `TabList` in page or a Dialog. `InkBar` is used in Aura theme, while the other themes are not using the inkBar in tabs, so other themes are unaffected.
I previously tried to add `this.updateInkBar()` in `updated` method but the animation seems a bit off.
**Using `updated`**
https://github.com/user-attachments/assets/7a7e0a89-e08a-4ef0-b222-d9720c13ebc0
So, I tried to use timeout and it looks better.
**Using `setTimeout` (this PR)**
https://github.com/user-attachments/assets/aa0eea73-dd43-42da-8a63-458949da41b7

Fixed #7224 - Wrong InkBar position when set default value in TabList

---

packages/primevue/src/galleria/GalleriaThumbnails.vue

Fixing #7021 by adding a threshold that needs to be reached before the motion triggers a swipe.
If the swipe is not triggered, then the normal click handler will correctly navigate to the next item.
Tested on Android

Fixed #7021 - Galleria: thumbnails don't work on mobile

---

packages/primevue/src/multiselect/MultiSelect.vue

fix: hide clear icon when options array is empty

---

packages/primevue/src/autocomplete/AutoComplete.vue
packages/primevue/src/cascadeselect/CascadeSelect.vue
packages/primevue/src/colorpicker/ColorPicker.vue
packages/primevue/src/confirmpopup/ConfirmPopup.vue
packages/primevue/src/contextmenu/ContextMenu.vue
packages/primevue/src/datatable/ColumnFilter.vue
packages/primevue/src/drawer/Drawer.vue
packages/primevue/src/megamenu/MegaMenu.vue
packages/primevue/src/menu/Menu.vue
packages/primevue/src/menubar/Menubar.vue
packages/primevue/src/multiselect/MultiSelect.vue
packages/primevue/src/popover/Popover.vue
packages/primevue/src/select/Select.vue
packages/primevue/src/tieredmenu/TieredMenu.vue
packages/primevue/src/treeselect/TreeSelect.vue

This commit addresses the issue where the overlay in components does not hide when clicking outside the component, if the click event is stopped using stopPropagation on an element or its parents.
The solution changes the event listener for detecting outside clicks to be triggered in the capture phase instead of the bubbling phase. This ensures that the outside click is correctly detected even if stopPropagation is called.
Fix  #7234

Fix: Trigger outsideClickListener in capture phase to handle stopPropagation

---

packages/primevue/src/datatable/DataTable.vue

Attempts to fix https://github.com/primefaces/primevue/issues/7227.
On a datatable that has the paginator enabled, with lazy=true, and selectionMode="multiple", then on the first page, shift-clicking multiple rows functions properly as expected by selecting all shift-clicked rows. However, when navigating to any page other than the first page, shift-clicking does NOT work, and instead cancels out any selection.
What's happening is that inside the [`selectRange()`](https://github.com/primefaces/primevue/blob/master/packages/primevue/src/datatable/DataTable.vue#L1190) method of datatable, `this.processedData` contains an array of data that is rendered on the current page of the table, and we use the indexes of rows that the user has shift+clicked in order to access the array by those …

Fix multi-row range selection on lazily paginated multi-selection Datatable (#7227)

---

packages/primevue/src/select/Select.vue

Fix https://github.com/primefaces/primevue/issues/7283
When using both `autoFilterFocus` and `autoOptionFocus` the first option would get focus for a brief moment, but then it would get unselected once the filter input gets the focus.
This change makes both of these work as expected - the input get focus and the first option is preselected.

fix(select): autoFilterFocus and autoOptionFocus working together

---

apps/showcase/components/layout/designer/create/DesignCreateTheme.vue
apps/showcase/components/layout/designer/dashboard/DesignDashboard.vue

Designer Updates

---

packages/primevue/src/button/Button.vue

#7325 
I'm not sure to understand what went wrong in #7123 as there is this css rule that hides the label if it's empty:
```
.p-button-icon-only .p-button-label {
visibility: hidden;
width: 0;
}
```
Putting back the span with an empty label would fix the buttons with only an icon.

Button with icon onyl - Rollback change from #7123

---

packages/primevue/src/selectbutton/SelectButton.vue

Makes the allowEmpty=false prop have different logic when the multiple prop is true. Prevents you from having an empty list 
[Issue#7358](https://github.com/primefaces/primevue/issues/7358)

make allowEmpty compatible with multiple on SelectButton

---

packages/primevue/src/multiselect/MultiSelect.vue

Fix https://github.com/primefaces/primevue/issues/7300
When using both autoFilterFocus and autoOptionFocus the first option would get focus for a brief moment, but then it would get unselected once the filter input gets the focus.
This change makes both of these work as expected - the input get focus and the first option is preselected.
Same as https://github.com/primefaces/primevue/pull/7282

fix(multi-select): autoFilterFocus and autoOptionFocus working together

---

packages/primevue/src/colorpicker/ColorPicker.vue

Fixes #4720 
My team and I came across Issue #4720 recently. I'll add a few more observations to describe this bug:
- The problem occurs when you drag the handle to the black color, as described by @cyhnkckali on Issue, which corresponds to the bottom edge of the selector. The left edge also causes the same behavior and corresponds to the different shades of gray, up to white. 
- The problem occurs when using the prop `format="hex"` (default) and `format="rgb"`. The problem is *not* reproduced when using `format="hsl"`.
This last point helps us understand where the problem comes from. Colors from white to black, and all shades of gray in between, are *hue-insensitive*. The hue selector can be set to any position, the color will always be the same.
However, the use of the prop …

Cache hue value locally on ColorPicker

---

packages/primevue/src/tablist/TabList.vue

Adds type="button" to the prev/next buttons in a tab list so that when used in a form these buttons do not submit the form

fix: tablist prev/next button type

---

packages/primevue/src/inputmask/InputMask.vue

fix InputMask when use unmask and in certain cases (empty string), will show wrong value

fix: InputMask #7378

---

packages/primevue/src/datatable/TableHeader.vue

**Issue**: `TableHeader.vue` was listening for `@change` from `FilterHeaderCell.vue`, but `FilterHeaderCell.vue` actually emits `checkbox-change`.
**Problem**: Since `TableHeader.vue` was expecting the wrong event, this was causing the event object arriving with undefined values, causing checkboxes to only unselect but never select.
**Fix**: This PR updates `TableHeader.vue` to listen for `checkbox-change`, ensuring checkboxes work correctly.
**Resolves**: [#7409](https://github.com/primefaces/primevue/issues/7409)

Fixed "multiple select" checkbox wrong listener in TableHeader

---

packages/primevue/src/dialog/Dialog.spec.js

Fix #7437 
Pr checker will fail due to another reason, please refer to https://github.com/primefaces/primevue/pull/7436.
It due to the `packages\nuxt-module\README.md` has some contents annotated under a list item, I've fixed it in that PR.

test(primevue): fix the failure about the `maximizable` of the `Dialog` component

---

packages/primevue/src/select/Select.vue

Fixed the issue that select cannot update value by clicking in datatable celledit mode
Replace @click with @mousedown
Resolves: https://github.com/primefaces/primevue/issues/7403

fix: Select cannot update(clicking) in Datatable(celledit mode) #7403

---

packages/primevue/src/tabpanel/TabPanel.vue

fix(primevue): fix the issue that wrong `id` of the `tab panel` component

---

packages/primevue/src/galleria/Galleria.vue

chore(primevue): enable to hide the fullscreen `galleria` component by `Escape`

---

packages/primevue/src/select/Select.vue

Small delay on blur handler to give enough time for the model to update from onOptionSelect(). This prevents the validation flicker issue because now the update value of the model is available when the blur event happens, and the formField.onBlur handler is called.
This related to this reported issue:
https://github.com/primefaces/primevue/issues/6906

Fixed issue in Select.vue

---

packages/primevue/src/virtualscroller/VirtualScroller.vue

Fix for this issue: https://github.com/primefaces/primevue/issues/7354
Since the VirtualScroller is not rendering the list on resize and on visibility change, I was thinking adding both a ResizeObserver and an IntersectionObserver. For the visibility, it seems counter intuitive to me adding an IntersectionObserver inside a Vue component. I think we could make a better usage of Vue `onMounted` hook.  
For now, I've added only a ResizeObserver that fixes the issue for both, resizing and conditional rendering (a v-show will necessarily trigger a resizing of the element).

fix: add resize observer on VirtualScroller component

---

packages/primevue/src/inputnumber/BaseInputNumber.vue
packages/primevue/src/inputnumber/InputNumber.vue

When used in a standard HTML `<form>`  element, a `required` tag is only recognized by the `InputText` component and not by the `InputNumber` component.
Since the `InputNumber` component is simply a wrapper around the `InputText` component, which itself supports the `required` prop, this is a very straightforward fix of simply accepting and passing the props on to the wrapped components.
The `allow-empty` prop tackles this from a different direction, however it resets the input field to 0 if emptied, which is a separate behaviour.  The `required` tag is recognized and validated natively by browsers, so it should be a part of all input fields, which is why this functionality is essential.

fix(InputNumber): added "required" prop which is present in wrapped component (InputText) already

---

packages/core/src/usestyle/UseStyle.js

For issue #6453 
This pull request includes an extra condition for tryOnMounted. It was made because getCurrentInstance returns an object that could have a isMounted: true flag value, but the value of the Vue application context properties, for example, 'components', could have null. So this fix is useful for module federation and can fix CSS variables problems that I described in the issue ahead.
This change improves the problem with CSS rules applying. There are some pictures before and after changes. It's from my MF Primevue example https://github.com/andrew-cmdltt/primevue-4-vite-issue-template-mf.
Before:
After:
So now these CSS rules are not undefined and attached to the head:

fix: add an extra condition for tryOnMounted method

---

packages/primevue/src/datatable/DataTable.vue

In the PrimeVue DataTable component, the top paginator's container template is missing the slotProps parameter. This causes a JavaScript error when users implement a custom paginatorcontainer slot because slotProps is referenced but not defined.
Add `="slotProps"` to the template definition for the container slot in both paginators to ensure consistent behavior and prevent errors when using custom paginator container templates.
Updated the template definition in the top paginator:
The bottom paginator already had the correct implementation: `#container="slotProps"`. This PR ensures both instances capture the slot props consistently.

Fix paginator container slot props in DataTable component

---

packages/primevue/src/colorpicker/ColorPicker.vue

Closes #7503
This PR resolves the regression added by #7291.
To test the proposed solution, add an input that will modify the color from outside the ColorPicker component.
```js
// apps/showcase/doc/colorpicker/BasicDoc.vue
<input type="text" v-model="color" />
```

Fix regression inserted by #7291 on ColorPicker

---

packages/primevue/src/fileupload/FileUpload.vue

fix(fileupload): fix the missing slot prop named `files` for the `filelabel` slot

---

apps/showcase/doc/autoimport/UnpluginDoc.vue

This fixes the code formatting in the UnPluginDoc.vue auto-import config example to improve readability. The previous formatting had an extra closing bracket that was misaligned, which could confuse users copying the example.

fix(docs): correct formatting for auto-import config example

---

packages/primevue/src/tooltip/Tooltip.js

I found a memory leak when using the tooltip directive and located the following code snippet:
In addition, a keydown event was not destroyed correctly.
I extracted the “onWindowResize“ method and handled it in a similar way to the other event listeners in the original code.
Of course, I also ran unit tests:

Fix the memory leak of the tooltip directive.

---

packages/primevue/src/multiselect/MultiSelect.d.ts

headercheckboxicon schema does not corresponds to the actual object return by slotProps.
`allSelected -> checked`
```ts
<MultiSelect>
<template #headercheckboxicon="slotProps">
{{ console.log(slotProps.checked) }}
</template>
</MultiSelect>
```

FIX - Multiselect slot schema

---

packages/primevue/src/confirmationoptions/ConfirmationOptions.d.ts

See the implementation:
https://github.com/primefaces/primevue/blob/5139f9f84ccafb82678d108150e29185e9c86a7c/packages/primevue/src/confirmdialog/ConfirmDialog.vue#L136

docs(confirmationoptions): fix default value for `modal`

---

packages/primevue/src/menu/Menu.d.ts
packages/primevue/src/menu/Menu.vue

chore(menu): enable to point out the exact `event.currentTarget` for the `show` and `toggle` methods

---

packages/primevue/src/select/Select.vue

Fix #7526 
At beginning, I want to change the `@mousedown` to `@click`, I found that here do exists a pr #7404  about it, so:
Use the `@click.stop` to stop the click event propagation to not to trigger the click event of the `.container` - `onContainerClick`

fix(select): fix the issue that cannot hide the overlay when `appendTo` equals `self`

---

packages/primevue/src/datatable/ColumnFilter.vue

So that we can use filterdisplay=menu with filters of single value (no operator and constraints)

fix: change matchmode in filter menu without constraints

---

packages/primevue/src/accordionheader/AccordionHeader.d.ts

Addresses: #7591
Update type definition of AccordionHeader with active prop to avoid linting errors.
With this PR in place - no more linting red squiggle:

fix(accordionheader): declare active prop in type definition for AccordionHeader

---

packages/primevue/src/colorpicker/ColorPicker.vue

Added event.preventDefault() to onHueDragStart(). Now by dragging hue selector it doesn't select background text/elements, before it stared selecting background elements when dragging mouse pass selector bounds.

FIX: ColorPicker hue selector.

---

packages/primevue/src/fileupload/FileUpload.vue

This PR fixes an issue where the `FileUpload` component automatically clear its file list after a successful custom upload (`@uploader`). The fix ensures that `clear()` is not called on case of custom upload, improving UX consistency with the standard upload flow.
Fixes [#7664](https://github.com/primefaces/primevue/pull/7662)

fix(FileUpload): clear file list after successful custom upload

---

packages/primevue/src/select/Select.vue

Added support for Backspace and Enter keys in the Editable Select component for mobile devices.
On mobile devices, keydown events were being blocked, preventing users from deleting text or confirming selections.
Modified the keyboard event handler to check for keyCode values (8 for Backspace, 13 for Enter) and allow these essential keys on mobile.
Tested on Android devices - backspace and enter keys now function properly.

fix(primevue): Add Backspace and Enter key support for mobile Editable Select

---

packages/primevue/src/toast/ToastMessage.vue

Fix for issue: #7683
Fix in toast message to avoid NaN when calculating message remaining life time on mouse enter.

Fix lifeRemaining calculation in ToastMessage to avoid NaN

---

packages/primevue/src/datatable/DataTable.vue

#Fix: https://github.com/primefaces/primevue/issues/7677
fixed: call d_columns.get() to avoid duplicate computed execution

fix: call d_columns.get() to avoid duplicate computed execution 

---

packages/primevue/src/select/Select.vue

Fix [#7613 Select: hitting ENTER when filter focused and no results breaks focus](https://github.com/primefaces/primevue/issues/7613)
This issue occurs because `this.hide()` is triggered with `isFocus: false` when the user presses Enter without any matching results, which causes the focused element to be lost. I moved the `this.hide()` call into the else block because, if the user does find a match and presses Enter, `this.hide()` would otherwise be invoked twice.

fix: keep focus when enter without any matchings

---

packages/primevue/src/datatable/DataTable.vue

Refactored the exportCSV(options, data) method to separate concerns. The new generateCSV(options, data) method now returns the CSV string without triggering a download. The updated exportCSV() method delegates CSV generation to generateCSV() and handles only the export logic. This makes the CSV data reusable for other purposes like copying, previewing, or sending via API.

separate CSV generation from exportCSV method

---

packages/forms/src/useform/index.js

Forms: setValues fails when an object with one or more properties that are not part of the form fields is provided.
This will just set properties if they are part of the form and ignore the rest.

Forms: add setFieldValue null check 

---

.github/PULL_REQUEST_TEMPLATE.md

I noticed when submitting another PR the headers were written as `###Defect Fixes` and `###Feature Requests` because of missing space.

Update PR template for headings

---

apps/showcase/doc/cdn/ExampleDoc.vue

In one of the examples, `PrimeUIX.Themes.Aura` should be used instead of `PrimeVue.Themes.Aura`

fix(ExampleDoc.vue): theme reference

---

apps/showcase/doc/introduction/ThemingDoc.vue

This PR fixes a broken link to the Tailwind Presets documentation in the Styling section.

fix(ThemingDoc): tailwind presets link broken

---

packages/primevue/src/menubar/MenubarSub.vue

fix #7704
Fixes accessibility issue on menu items of component MenuBar, the `aria-level` attribute is not valid for the role `menuitem`.
Check https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-level documentation for reference.

fix(MenubarSub): aria-level invalid attribute for role menuitem

---

packages/primevue/src/chip/Chip.vue

fix #7699
As described in the reported issue, the label was not displayed when its value was 0, so I modified the condition to explicitly check for null.

fix(chip): modified the label visibility condition

---

packages/primevue/src/datepicker/DatePicker.vue
packages/primevue/src/multiselect/MultiSelect.vue

DatePicker & MultiSelect fixed
https://github.com/primefaces/primevue/issues/7661
When using keyboard navigation within a dialog, pressing the "ESC" key after interacting with a DatePicker or MultiSelect component closes the entire dialog instead of just closing the DatePicker or MultiSelect. This behavior makes it difficult for users to continue working within the dialog after dismissing these components.

DatePicker & MultiSelect: esc keypress propagates and triggers close in dialogs

---

packages/primevue/src/datatable/BodyCell.vue

当点击 DataTable 行中的展开按钮时，点击事件会冒泡并触发行点击事件处理器，导致意外行为。
When clicking the expander button in a DataTable row, the click event bubbles up and triggers the row-click event handler, causing unintended behavior.
1. 创建一个带有可展开行的 DataTable（使用 `expander` 列）
Create a DataTable with expandable rows (using `expander` column)
2. 为 DataTable 添加行点击事件处理器
Add a row-click event handler to the DataTable
3. 点击展开按钮来展开/折叠行
Click on the expander button to expand/collapse a row
4. 观察到行点击事件也被触发了
Observe that the row-click event is also triggered
- 点击展开按钮应该只触发展开/折叠功能
Clicking the expander button should only trigger the expand/collapse functionality
- 点击展开按钮时不应触发行点击事件
Row-click events should NOT be triggered when clicking the expander button
- 只有直接点击行（操作按钮外）才应触发行点击事件
Only direct clicks on the row (outside of action …

Fix DataTable expander button triggering unwanted row-click events

---

packages/primevue/src/datepicker/DatePicker.vue

fix #7691 
In a DatePicker with multiple months, calendars are displayed starting from the `viewDate` for the number of months defined by `numberOfMonths`.
Currently, selecting the second date updates the `viewDate`, which unintentionally shifts the visible calendar and can disrupt the user’s selection flow.
To improve this, I updated the logic to retain the initial `viewDate` if the second date falls within the range from the first selected date to the number of months specified by `numberOfMonths`. However, if the calendar has been navigated using the next button, it will display months starting from the second selected date instead.

fix(datepicker): keep current month visible when selecting a range

---

packages/primevue/src/dialog/Dialog.vue

fix: allow dialog to close on escape when closable is false 

---

packages/nuxt-module/src/module.ts

Resolves #7797  
Resolves #7918
With Nuxt 4 on the horizon, this updates the module compatibility definition to allow it to be installed on Nuxt v4. (Otherwise Nuxt will indicate the module might not be compatible.)
When Nuxt v4 comes out then you might decide or need to make breaking changes in this module and release a new major, but hopefully the migration should be smoother. 🙏
👉 You can follow this and other changes in https://github.com/nuxt/nuxt/issues/27613 - please feel free to provide feedback as well!

chore: indicate compatibility with Nuxt v4 major

---

packages/primevue/src/tree/TreeNode.vue

Fixes #7905 
Fixes #7899 
The `TreeNode` component did not pass the `index` value to child nodes leading to accessibility issues with the `aria-posinset` value being set to the default value (i.e., `NaN`). 
This change passes the `index` value to child nodes in the `TreeNode` component such that the `aria-posinset` value is set correctly.

fix: pass index to child TreeNodes

---

packages/primevue/src/colorpicker/ColorPicker.vue

Fix https://github.com/primefaces/primevue/issues/7933
Solving issue where previous PR 7511 is looking at overlayVisible, however this will always be false if inline.
To recreate bug:
In apps/showcase/doc/colorpicker/InlineDoc.vue
add 
`<div :style="{ backgroundColor: `#${color}` }">{{ color }}</div>`
And check that i gets wrong color selections by dragging selection to left and then back to middle.

Make sure overlayVisible check only applies for non inline color picker

---

packages/primevue/src/multiselect/MultiSelect.vue

Makes the modelValue set to an empty array instead of null when the clear icon is pressed.
This now follows the same logic that happens when you toggle the checkbox at the top to select/deselect all

fix(MutliSelect): update model to empty array on clear click

---

apps/volt/volt/Checkbox.vue

Fix the Style of the Checkbox in Dark Mode
The check icon was not visible in darkmode when checkbox was disabled.
> dark:p-disabled:bg-surface-400
> dark:p-disabled:text-surface-400
Also tried to add matching style for light/dark mode for disabled checkboxes.
(same problem as in [https://github.com/primefaces/primevue-tailwind/pull/371](https://github.com/primefaces/primevue-tailwind/pull/371) but hopefullly fixed correctly this time)
BEFORE:
AFTER:
https://volt.primevue.org/checkbox/#disabled

fix style of checkbox icon when disabled (volt)

---

apps/showcase/doc/dialog/HeadlessDoc.vue
packages/primevue/src/dialog/Dialog.d.ts
packages/primevue/src/dialog/Dialog.vue

Fixes [#7892](https://github.com/primefaces/primevue/issues/7892)
The problem was that dragging was not possible when using the container slot in the Dialog component, since initDrag was not exposed to the slot scope.
Fixed by passing initDragCallback to the container slot. Also updated TypeScript types and documentation accordingly.
Now dragging works even when customizing the dialog via the container slot.

fix(dialog): enabled dragging when using container template

---

packages/primevue/src/datepicker/DatePicker.vue

Fixes #7995 -- unformatted dates are being displayed if the user clicks on the same date as the one that's already selected. This issue manifests itself only when DatePicker is used with forms.
This happens because the value displayed on the input is a computed value (in `primevue/src/datepicker/DatePicker.vue`):
```
inputFieldValue() {
return this.formatValue(this.d_value);
},
```
But `useForm`'s `defineField` has an event listener that modifies the field's value directly (in `forms/src/useform/index.js`):
```
onChange: (event) => {
_states[field].value = event && Object.hasOwn(event, 'value') ? event.value : event.target.type === 'checkbox' || event.target.type === 'radio' ? event.target.checked : event.target.value;
},
```
If the same date is selected, a change event is still fired, …

Fix #7995 - unformatted date being displayed when clicking on the same date

---

packages/core/src/utils/HelperSet.js
packages/primevue/src/datatable/DataTable.spec.js
packages/primevue/src/datatable/DataTable.vue

Fixes #4940 
Fixes #5190
Fixes #4646 again
This enables primevue users to Column defaults like sorticons once.
Unfortunately this reverts the (unreleased) changes from this commit: https://github.com/primefaces/primevue/commit/9bdf762746b509cb9041aff54ed505a9315cb826
The columns first needs to be rendered before they are added to the column helperset, only then their helpers can be used to filter the DataTable computed columns. 
I'm open to suggestions how this can be achieved without the extra computed tick.

fix: Allow wrapped datatable columns

---

apps/showcase/doc/common/apidoc/index.json
packages/primevue/src/drawer/BaseDrawer.vue
packages/primevue/src/drawer/Drawer.d.ts
packages/primevue/src/drawer/Drawer.vue

This PR adds a new closeOnEscape prop to the Drawer component. 
By default it is true (current behavior), but setting it to false prevents the Drawer from closing when pressing Escape.

feat(drawer): add closeOnEscape prop to control closing on Escape Key

---

packages/primevue/src/panel/Panel.d.ts
packages/primevue/src/panel/Panel.vue

Panel component has a number of slots.
The header slot is missing the collapsed state.

Add collapsed to panel header slot

---

packages/primevue/src/image/Image.d.ts

#8140 
The Image component docs incorrectly listed `show`, `hide`, and `error` under **Methods**.  
They are actually **emits**. Updated the docs accordingly.

fix(image): consolidate emits options and methods

---

packages/primevue/src/checkbox/Checkbox.vue

Storybook’s [accessibility addon](https://storybook.js.org/docs/writing-tests/accessibility-testing) identifies problems with the way the PrimeVue Checkbox component manages its indeterminate state. The implementation currently applies **aria-checked="mixed"** to the internal input element. This is problematic because native input **type="checkbox"** elements do not support **aria-checked**, that attribute is reserved for custom controls that mimic checkboxes. For native checkboxes, the correct method is to set the indeterminate state via the element’s indeterminate property.
Relevant issue: https://github.com/primefaces/primevue/issues/8142

Indicate indeterminate state with prop iso aria-checked attr

---

packages/primevue/src/drawer/Drawer.vue

Storybook’s [accessibility addon](https://storybook.js.org/docs/writing-tests/accessibility-testing) identifies problems with the PrimeVue Drawer use of both role="complementary" and aria-modal attributes.
I understand that role="complementary" is a landmark role for persistent, supporting content like sidebars, while aria-modal="true" is reserved for temporary overlays that block background interaction and trap focus. These meanings conflict: complementary implies ongoing accessibility, whereas modal implies temporary exclusivity. WAI-ARIA therefore restricts aria-modal to dialog, alertdialog, and window.
If the Drawer is modal, then use role="dialog" and aria-modal="true".
If not modal, then use role="complementary" and don't set aria-modal at all.
Relevant issue: …

Change role of Drawer depending if its modal or not
